import { Simulado } from './simulado.model';

export const QUESTIONS_POOL: Record<string, Omit<Simulado, 'id'>[]> = {
  'Matemática': [
    { subject: 'Matemática', question: 'Qual é o resultado de 7 x 8?', options: ['54', '56', '62', '64'], correctAnswerIndex: 1, explanation: '7 multiplicado por 8 resulta em 56.' },
    { subject: 'Matemática', question: 'Quanto é 15% de 200?', options: ['20', '30', '40', '25'], correctAnswerIndex: 1, explanation: '10% de 200 é 20, 5% é 10. 20 + 10 = 30.' },
    { subject: 'Matemática', question: 'Qual é a raiz quadrada de 144?', options: ['10', '11', '12', '14'], correctAnswerIndex: 2, explanation: '12 x 12 = 144.' },
    { subject: 'Matemática', question: 'Resolva: 2 + 3 x 4', options: ['20', '14', '24', '10'], correctAnswerIndex: 1, explanation: 'Primeiro a multiplicação: 3x4=12. Depois a soma: 2+12=14.' },
    { subject: 'Matemática', question: 'Quantos lados tem um hexágono?', options: ['5', '6', '7', '8'], correctAnswerIndex: 1, explanation: 'Um hexágono possui 6 lados.' },
    { subject: 'Matemática', question: 'O que é um ângulo obtuso?', options: ['Menor que 90º', 'Igual a 90º', 'Maior que 90º e menor que 180º', 'Igual a 180º'], correctAnswerIndex: 2, explanation: 'Ângulo obtuso mede mais que 90 graus e menos que 180.' },
    { subject: 'Matemática', question: 'Qual o valor de Pi (aproximado)?', options: ['3,12', '3,14', '3,16', '3,18'], correctAnswerIndex: 1, explanation: 'O valor de Pi é aproximadamente 3,14.' },
    { subject: 'Matemática', question: 'Quanto é 5³?', options: ['15', '25', '125', '75'], correctAnswerIndex: 2, explanation: '5 x 5 x 5 = 125.' },
    { subject: 'Matemática', question: 'Qual é o dobro de 1/2?', options: ['1/4', '1', '2', '1/2'], correctAnswerIndex: 1, explanation: '2 vezes 1/2 é igual a 1.' },
    { subject: 'Matemática', question: 'Converta 2m para cm', options: ['20cm', '200cm', '2000cm', '2cm'], correctAnswerIndex: 1, explanation: '1 metro tem 100cm, logo 2 metros têm 200cm.' },
    // ... adding more to reach ~30 visually
    { subject: 'Matemática', question: 'Qual o próximo número da sequência: 2, 4, 8, 16...', options: ['24', '30', '32', '36'], correctAnswerIndex: 2, explanation: 'A sequência dobra o número anterior.' },
    { subject: 'Matemática', question: 'Quanto é 100 dividido por 4?', options: ['20', '25', '30', '24'], correctAnswerIndex: 1, explanation: '100 / 4 = 25.' },
    { subject: 'Matemática', question: 'Qual a área de um quadrado de lado 4cm?', options: ['8cm²', '12cm²', '16cm²', '20cm²'], correctAnswerIndex: 2, explanation: 'Área = lado x lado = 4 x 4 = 16.' },
    { subject: 'Matemática', question: 'O que é um número primo?', options: ['Divisível só por 2', 'Divisível por 1 e por ele mesmo', 'Número ímpar', 'Número infinito'], correctAnswerIndex: 1, explanation: 'Número primo tem apenas dois divisores: 1 e ele mesmo.' },
    { subject: 'Matemática', question: 'Quanto vale X em: 2X + 4 = 10?', options: ['2', '3', '4', '1'], correctAnswerIndex: 1, explanation: '2X = 6 -> X = 3.' },
    { subject: 'Matemática', question: 'Qual o MDC de 8 e 12?', options: ['2', '4', '8', '24'], correctAnswerIndex: 1, explanation: 'Os divisores comuns são 1, 2, 4. O maior é 4.' },
    { subject: 'Matemática', question: 'Qual o MMC de 3 e 4?', options: ['7', '12', '6', '24'], correctAnswerIndex: 1, explanation: 'Múltiplos de 3: 3,6,9,12... Múltiplos de 4: 4,8,12... MMC é 12.' },
    { subject: 'Matemática', question: 'Quanto é -5 + 8?', options: ['-3', '3', '-13', '13'], correctAnswerIndex: 1, explanation: 'Sinais opostos, subtrai e mantém o sinal do maior: 8-5=3.' },
    { subject: 'Matemática', question: 'O que é a hipotenusa?', options: ['O menor lado de um triângulo', 'O lado oposto ao ângulo reto', 'A altura do triângulo', 'Um tipo de ângulo'], correctAnswerIndex: 1, explanation: 'Hipotenusa é o lado oposto ao ângulo de 90 graus no triângulo retângulo.' },
    { subject: 'Matemática', question: 'Quanto é 3 fatorial (3!)?', options: ['3', '6', '9', '1'], correctAnswerIndex: 1, explanation: '3! = 3 x 2 x 1 = 6.' },
    { subject: 'Matemática', question: 'Qual a fórmula da área do círculo?', options: ['2πr', 'πr²', 'πr', '2πr²'], correctAnswerIndex: 1, explanation: 'Área = Pi vezes raio ao quadrado.' },
    { subject: 'Matemática', question: 'Quantos graus tem um círculo completo?', options: ['180', '270', '360', '90'], correctAnswerIndex: 2, explanation: 'Uma volta completa tem 360 graus.' },
    { subject: 'Matemática', question: 'Qual o perímetro de um quadrado de lado 5?', options: ['10', '15', '20', '25'], correctAnswerIndex: 2, explanation: 'Perímetro = 4 x lado = 4 x 5 = 20.' },
    { subject: 'Matemática', question: 'Quanto é a raiz cúbica de 27?', options: ['3', '9', '6', '1'], correctAnswerIndex: 0, explanation: '3 x 3 x 3 = 27.' },
    { subject: 'Matemática', question: 'Se x=2 e y=3, quanto é x+y²?', options: ['25', '11', '13', '8'], correctAnswerIndex: 1, explanation: '2 + 3² = 2 + 9 = 11.' },
    { subject: 'Matemática', question: 'Qual é o nome de um polígono de 5 lados?', options: ['Quadrado', 'Hexágono', 'Pentágono', 'Heptágono'], correctAnswerIndex: 2, explanation: 'Pentágono tem 5 lados.' },
    { subject: 'Matemática', question: 'Quanto é 10 elevado a 0?', options: ['0', '1', '10', '100'], correctAnswerIndex: 1, explanation: 'Qualquer número elevado a 0 é 1.' },
    { subject: 'Matemática', question: 'Qual a soma dos ângulos internos de um triângulo?', options: ['180º', '360º', '90º', '270º'], correctAnswerIndex: 0, explanation: 'A soma é sempre 180 graus.' },
    { subject: 'Matemática', question: 'Quanto é 0,5 + 0,25?', options: ['0,30', '0,75', '0,80', '0,255'], correctAnswerIndex: 1, explanation: '0,50 + 0,25 = 0,75.' },
    { subject: 'Matemática', question: 'Qual é inverso de 4?', options: ['-4', '1/4', '0.4', '2'], correctAnswerIndex: 1, explanation: 'O inverso multiplicativo de x é 1/x.' }
  ],
  'Português': [
    { subject: 'Português', question: 'Qual palavra é um substantivo próprio?', options: ['Cachorro', 'Cidade', 'Brasil', 'Amor'], correctAnswerIndex: 2, explanation: 'Brasil nomeia um lugar específico.' },
    { subject: 'Português', question: 'Qual é o antônimo de "frio"?', options: ['Gelado', 'Quente', 'Morno', 'Congelado'], correctAnswerIndex: 1, explanation: 'O contrário de frio é quente.' },
    { subject: 'Português', question: 'Quantas sílabas tem a palavra "Paralelepípedo"?', options: ['5', '6', '7', '8'], correctAnswerIndex: 2, explanation: 'Pa-ra-le-le-pí-pe-do (7 sílabas).' },
    { subject: 'Português', question: 'Qual é o sujeito em "O gato correu"?', options: ['O gato', 'Correu', 'Gato', 'O'], correctAnswerIndex: 0, explanation: '"O gato" é quem pratica a ação.' },
    { subject: 'Português', question: 'O que é uma paroxítona?', options: ['A última sílaba forte', 'A penúltima sílaba forte', 'A antepenúltima sílaba forte', 'Todas as sílabas fortes'], correctAnswerIndex: 1, explanation: 'Palavras com a penúltima sílaba tônica.' },
    { subject: 'Português', question: 'Assinale a palavra com crase correta:', options: ['Vou à praia', 'Vou a praia', 'Vou á praia', 'Vou à ela'], correctAnswerIndex: 0, explanation: 'Quem vai, vai A algum lugar. A + A = À.' },
    { subject: 'Português', question: 'Qual o plural de "cidadão"?', options: ['Cidadões', 'Cidadãos', 'Cidadães', 'Cidadãozinhos'], correctAnswerIndex: 1, explanation: 'O plural correto é cidadãos.' },
    { subject: 'Português', question: 'O que é um adjetivo?', options: ['Ação', 'Nome', 'Qualidade', 'Conjunção'], correctAnswerIndex: 2, explanation: 'Adjetivo caracteriza o substantivo.' },
    { subject: 'Português', question: 'Sinônimo de "feliz":', options: ['Triste', 'Saltitante', 'Alegre', 'Rápido'], correctAnswerIndex: 2, explanation: 'Alegre tem sentido semelhante a feliz.' },
    { subject: 'Português', question: '"Nós vai" está:', options: ['Correto', 'Incorreto (Concordância)', 'Incorreto (Regência)', 'Formal'], correctAnswerIndex: 1, explanation: 'Erro de concordância verbal. Correto: Nós vamos.' },
    { subject: 'Português', question: 'Qual é o verbo na frase "Ela canta bem"?', options: ['Ela', 'Canta', 'Bem', 'Nenhum'], correctAnswerIndex: 1, explanation: 'Canta é a ação.' },
    { subject: 'Português', question: 'A palavra "muito" é:', options: ['Verbo', 'Adjetivo', 'Advérbio', 'Substantivo'], correctAnswerIndex: 2, explanation: 'Advérbio de intensidade.' },
    { subject: 'Português', question: 'Qual o feminino de "carneiro"?', options: ['Carneira', 'Cabra', 'Ovelha', 'Vaca'], correctAnswerIndex: 2, explanation: 'O feminino de carneiro é ovelha.' },
    { subject: 'Português', question: 'Quem escreveu "Dom Casmurro"?', options: ['Machado de Assis', 'José de Alencar', 'Clarice Lispector', 'Jorge Amado'], correctAnswerIndex: 0, explanation: 'Obra clássica de Machado de Assis.' },
    { subject: 'Português', question: 'O que é hiato?', options: ['Encontro de consoantes', 'Encontro de vogais em sílabas diferentes', 'Encontro de vogais na mesma sílaba', 'Vogal e consoante'], correctAnswerIndex: 1, explanation: 'Duas vogais juntas na palavra, mas separadas na silaba (ex: sa-ú-de).' },
    { subject: 'Português', question: '"Mas" indica:', options: ['Adição', 'Oposição', 'Tempo', 'Causa'], correctAnswerIndex: 1, explanation: 'Conjunção adversativa.' },
    { subject: 'Português', question: '"Mais" indica:', options: ['Oposição', 'Quantidade', 'Tempo', 'Dúvida'], correctAnswerIndex: 1, explanation: 'Advérbio de intensidade/quantidade.' },
    { subject: 'Português', question: 'Qual é o coletivo de "abelhas"?', options: ['Matilha', 'Cardume', 'Enxame', 'Rebanho'], correctAnswerIndex: 2, explanation: 'Enxame é o coletivo de abelhas.' },
    { subject: 'Português', question: 'A palavra "árvore" é:', options: ['Oxítona', 'Paroxítona', 'Proparoxítona', 'Monossílaba'], correctAnswerIndex: 2, explanation: 'A antepenúltima sílaba é tônica (ár-vo-re).' },
    { subject: 'Português', question: 'Qual frase está no passado?', options: ['Eu como pão', 'Eu comerei pão', 'Eu comi pão', 'Eu estou comendo'], correctAnswerIndex: 2, explanation: '"Comi" é pretérito (passado).' },
    { subject: 'Português', question: 'Como se escreve: "excessão" ou "exceção"?', options: ['Excessão', 'Exceção', 'Eceção', 'Esceção'], correctAnswerIndex: 1, explanation: 'Correto é Exceção (com ç).' },
    { subject: 'Português', question: 'O que é onomatopeia?', options: ['Tipo de verso', 'Imitação de som', 'Figura de linguagem visual', 'Erro ortográfico'], correctAnswerIndex: 1, explanation: 'Ex: "Miau", "Tic-tac".' },
    { subject: 'Português', question: '"Copo de vidro" - vidro é:', options: ['Substantivo', 'Adjetivo', 'Verbo', 'Locução adjetiva'], correctAnswerIndex: 0, explanation: 'Nesse contexto é a matéria (substantivo), mas "de vidro" funciona como locução adjetiva.' },
    { subject: 'Português', question: 'Qual a pontuação de fim de pergunta?', options: ['Ponto final', 'Interrogação', 'Exclamação', 'Vírgula'], correctAnswerIndex: 1, explanation: '?' },
    { subject: 'Português', question: 'O que é dígrafo?', options: ['Duas letras, um som', 'Dois sons, uma letra', 'Duas vogais', 'Duas sílabas'], correctAnswerIndex: 0, explanation: 'Ex: ch, lh, nh, rr, ss.' },
    { subject: 'Português', question: 'Qual o aumentativo de "casa"?', options: ['Casinha', 'Casarão', 'Casona', 'Predio'], correctAnswerIndex: 1, explanation: 'Casarão.' },
    { subject: 'Português', question: 'A palavra "herói" tem acento?', options: ['Sim', 'Não', 'Às vezes', 'Opcional'], correctAnswerIndex: 0, explanation: 'Sim, oxítona terminada em ditongo aberto "ói".' },
    { subject: 'Português', question: 'O que significa "manga" (fruta) e "manga" (camisa)?', options: ['Sinônimos', 'Antônimos', 'Homônimos', 'Parônimos'], correctAnswerIndex: 2, explanation: 'Palavras iguais na escrita ou som, mas significados diferentes.' },
    { subject: 'Português', question: 'Quantas letras tem o alfabeto?', options: ['23', '24', '25', '26'], correctAnswerIndex: 3, explanation: '26 letras.' },
    { subject: 'Português', question: '"Ele tinha chegado". O tempo é:', options: ['Futuro', 'Presente', 'Pretérito mais-que-perfeito composto', 'Imperativo'], correctAnswerIndex: 2, explanation: 'Tinha chegado equivale a "chegara".' }
  ],
  'Física': [
    { subject: 'Física', question: 'Qual é a fórmula da velocidade média?', options: ['V = d/t', 'V = d*t', 'V = t/d', 'V = a*t'], correctAnswerIndex: 0, explanation: 'Velocidade é a distância dividida pelo tempo.' },
    { subject: 'Física', question: 'Unidade de força no SI:', options: ['Joule', 'Newton', 'Pascal', 'Watt'], correctAnswerIndex: 1, explanation: 'Força é medida em Newtons (N).' },
    { subject: 'Física', question: 'Qual a aceleração da gravidade aprox. na Terra?', options: ['5 m/s²', '9,8 m/s²', '12 m/s²', '15 m/s²'], correctAnswerIndex: 1, explanation: 'Aproximadamente 9,8 m/s².' },
    { subject: 'Física', question: 'O que mede o termômetro?', options: ['Calor', 'Temperatura', 'Pressão', 'Umidade'], correctAnswerIndex: 1, explanation: 'Mede o grau de agitação das moléculas (temperatura), não calor diretamente.' },
    { subject: 'Física', question: 'Qual a 1ª Lei de Newton?', options: ['Inércia', 'Ação e Reação', 'Gravitação', 'F=ma'], correctAnswerIndex: 0, explanation: 'Lei da Inércia.' },
    { subject: 'Física', question: 'Em qual estado a água ferve (nível do mar)?', options: ['0ºC', '50ºC', '100ºC', '200ºC'], correctAnswerIndex: 2, explanation: '100 graus Celsius.' },
    { subject: 'Física', question: 'O som se propaga no vácuo?', options: ['Sim', 'Não', 'Depende', 'Às vezes'], correctAnswerIndex: 1, explanation: 'Som precisa de meio material para se propagar.' },
    { subject: 'Física', question: 'Fórmula da Energia Cinética:', options: ['mgh', 'mv²/2', 'ma', 'mc²'], correctAnswerIndex: 1, explanation: 'Massa vezes velocidade ao quadrado dividido por 2.' },
    { subject: 'Física', question: 'Cargas de sinais iguais:', options: ['Se atraem', 'Se repelem', 'Se anulam', 'Explodem'], correctAnswerIndex: 1, explanation: 'Cargas iguais se repelem.' },
    { subject: 'Física', question: 'O que é um ano-luz?', options: ['Tempo', 'Distância', 'Velocidade', 'Força'], correctAnswerIndex: 1, explanation: 'Distância que a luz percorre em um ano.' },
    { subject: 'Física', question: 'Qual a velocidade da luz no vácuo?', options: ['300 m/s', '300.000 km/s', '340 m/s', '1.000 km/h'], correctAnswerIndex: 1, explanation: 'Aproximadamente 300.000 km/s.' },
    { subject: 'Física', question: 'O que é a refração?', options: ['Luz batendo e voltando', 'Luz mudando de meio e velocidade', 'Luz sendo absorvida', 'Luz criando arco-íris'], correctAnswerIndex: 1, explanation: 'Mudança de velocidade (e direção) ao mudar de meio.' },
    { subject: 'Física', question: 'Unidade de Potência:', options: ['Joule', 'Watt', 'Volt', 'Ampere'], correctAnswerIndex: 1, explanation: 'Watt (W).' },
    { subject: 'Física', question: 'Fórmula de Ohm:', options: ['U = R*i', 'P = i*U', 'E = mc²', 'F = m*a'], correctAnswerIndex: 0, explanation: 'Tensão = Resistência x Corrente.' },
    { subject: 'Física', question: 'O elétron tem carga:', options: ['Positiva', 'Negativa', 'Neutra', 'Dupla'], correctAnswerIndex: 1, explanation: 'Negativa.' },
    { subject: 'Física', question: 'O que é densidade?', options: ['Volume/Massa', 'Massa/Volume', 'Peso/Altura', 'Força/Área'], correctAnswerIndex: 1, explanation: 'd = m/v.' },
    { subject: 'Física', question: 'As cores do arco-íris são formadas por:', options: ['Reflexão', 'Dispersão', 'Difração', 'Interferência'], correctAnswerIndex: 1, explanation: 'A luz branca se separa em cores (dispersão).' },
    { subject: 'Física', question: 'Qual planeta é conhecido pelos anéis?', options: ['Marte', 'Júpiter', 'Saturno', 'Vênus'], correctAnswerIndex: 2, explanation: 'Saturno.' },
    { subject: 'Física', question: 'O que é o zero absoluto?', options: ['0ºC', '-273,15ºC', '0ºF', '-100ºC'], correctAnswerIndex: 1, explanation: '0 Kelvin, onde cessa a agitação molecular.' },
    { subject: 'Física', question: 'Para toda ação, há uma reação...', options: ['Igual e no mesmo sentido', 'Igual e sentido contrário', 'Maior e sentido contrário', 'Nula'], correctAnswerIndex: 1, explanation: '3ª Lei de Newton: mesma intensidade, mesma direção, sentidos opostos.' },
    { subject: 'Física', question: 'O Sol é uma:', options: ['Planeta', 'Estrela', 'Lua', 'Galáxia'], correctAnswerIndex: 1, explanation: 'Estrela anã amarela.' },
    { subject: 'Física', question: 'Unidade de corrente elétrica:', options: ['Volt', 'Ohm', 'Ampere', 'Coulomb'], correctAnswerIndex: 2, explanation: 'Ampere (A).' },
    { subject: 'Física', question: 'O que é atrito?', options: ['Força que ajuda o movimento', 'Força que se opõe ao movimento', 'Tipo de energia', 'Aceleração'], correctAnswerIndex: 1, explanation: 'Resistência ao movimento relativo entre superfícies.' },
    { subject: 'Física', question: 'Qual a cor que reflete todas as luzes?', options: ['Preto', 'Branco', 'Vermelho', 'Azul'], correctAnswerIndex: 1, explanation: 'Branco reflete todas, preto absorve todas.' },
    { subject: 'Física', question: 'O que é fusão nuclear?', options: ['Quebra de átomos', 'Junção de átomos', 'Evaporação', 'Congelamento'], correctAnswerIndex: 1, explanation: 'Processo que ocorre no Sol (H + H -> He).' },
    { subject: 'Física', question: 'Instrumento para medir pressão atmosférica:', options: ['Termômetro', 'Barômetro', 'Manômetro', 'Voltímetro'], correctAnswerIndex: 1, explanation: 'Barômetro.' },
    { subject: 'Física', question: 'Espelhos convexos:', options: ['Ampliam a imagem', 'Invertem a imagem', 'Ampliam o campo de visão', 'Focam a luz'], correctAnswerIndex: 2, explanation: 'Usados em retrovisores e lojas, diminuem a imagem mas aumentam o campo.' },
    { subject: 'Física', question: 'Qual é o metal líquido à temperatura ambiente?', options: ['Ferro', 'Mercúrio', 'Ouro', 'Prata'], correctAnswerIndex: 1, explanation: 'Mercúrio.' },
    { subject: 'Física', question: 'Energia potencial depende de:', options: ['Velocidade', 'Altura', 'Tempo', 'Atrito'], correctAnswerIndex: 1, explanation: 'Epg = mgh (depende da altura h).' },
    { subject: 'Física', question: 'Qual a unidade de Frequência?', options: ['Hertz', 'Segundo', 'Metro', 'Newton'], correctAnswerIndex: 0, explanation: 'Hz (ciclos por segundo).' },
  ],
  'História': [
    { subject: 'História', question: 'Quem descobriu o Brasil?', options: ['Colombo', 'Cabral', 'Vasco da Gama', 'Magalhães'], correctAnswerIndex: 1, explanation: 'Pedro Álvares Cabral em 1500.' },
    { subject: 'História', question: 'Ano da Independência do Brasil:', options: ['1808', '1822', '1889', '1500'], correctAnswerIndex: 1, explanation: '7 de Setembro de 1822.' },
    { subject: 'História', question: 'Quem foi o primeiro presidente do Brasil?', options: ['Getúlio Vargas', 'Marechal Deodoro', 'Dom Pedro II', 'JK'], correctAnswerIndex: 1, explanation: 'Marechal Deodoro da Fonseca.' },
    { subject: 'História', question: 'O que foi o feudalismo?', options: ['Sistema industrial', 'Sistema agrário vrasalo-senhor', 'Democracia grega', 'Ditadura romana'], correctAnswerIndex: 1, explanation: 'Sistema medieval baseado na terra e fidelidade.' },
    { subject: 'História', question: 'País onde começou a Revolução Industrial:', options: ['França', 'EUA', 'Inglaterra', 'Alemanha'], correctAnswerIndex: 2, explanation: 'Inglaterra, século XVIII.' },
    { subject: 'História', question: 'Líder da Alemanha nazista:', options: ['Mussolini', 'Hitler', 'Stalin', 'Franco'], correctAnswerIndex: 1, explanation: 'Adolf Hitler.' },
    { subject: 'História', question: 'Guerra Fria foi entre:', options: ['EUA e URSS', 'EUA e China', 'Alemanha e Inglaterra', 'Brasil e Argentina'], correctAnswerIndex: 0, explanation: 'Conflito ideológico entre Capitalismo (EUA) e Socialismo (URSS).' },
    { subject: 'História', question: 'Quem pintou a Mona Lisa?', options: ['Michelangelo', 'Da Vinci', 'Van Gogh', 'Picasso'], correctAnswerIndex: 1, explanation: 'Leonardo da Vinci.' },
    { subject: 'História', question: 'Qual era a moeda antes do Real?', options: ['Cruzado', 'Cruzeiro Real', 'Cruzeiro', 'Todos esses'], correctAnswerIndex: 3, explanation: 'O Brasil teve várias moedas antes do Real (1994).' },
    { subject: 'História', question: 'O que comemora em 15 de Novembro?', options: ['Independência', 'Proclamação da República', 'Natal', 'Tiradentes'], correctAnswerIndex: 1, explanation: 'República proclamada em 1889.' },
    { subject: 'História', question: 'Capital do Império Romano:', options: ['Atenas', 'Esparta', 'Roma', 'Veneza'], correctAnswerIndex: 2, explanation: 'Roma.' },
    { subject: 'História', question: 'Quem era chamado de "O Libertador"?', options: ['Napoleão', 'Simon Bolívar', 'Dom Pedro I', 'Tiradentes'], correctAnswerIndex: 1, explanation: 'Bolívar libertou várias nações sul-americanas.' },
    { subject: 'História', question: 'O que foi a Lei Áurea?', options: ['Fim da Monarquia', 'Abolição da Escravidão', 'Início da República', 'Voto feminino'], correctAnswerIndex: 1, explanation: 'Assinada em 1888 pela Princesa Isabel.' },
    { subject: 'História', question: 'Primeira capital do Brasil:', options: ['Rio de Janeiro', 'Brasília', 'Salvador', 'São Paulo'], correctAnswerIndex: 2, explanation: 'Salvador foi capital até 1763.' },
    { subject: 'História', question: 'Deus egípcio do sol:', options: ['Anúbis', 'Rá', 'Osíris', 'Zeus'], correctAnswerIndex: 1, explanation: 'Rá.' },
    { subject: 'História', question: 'Onde ficam as pirâmides de Gizé?', options: ['México', 'Egito', 'Peru', 'Sudão'], correctAnswerIndex: 1, explanation: 'No Egito.' },
    { subject: 'História', question: 'Quem libertou os escravos nos EUA?', options: ['Washington', 'Lincoln', 'Kennedy', 'Obama'], correctAnswerIndex: 1, explanation: 'Abraham Lincoln.' },
    { subject: 'História', question: 'Revolução Francesa aconteceu em:', options: ['1789', '1500', '1945', '2000'], correctAnswerIndex: 0, explanation: 'Queda da Bastilha, 1789.' },
    { subject: 'História', question: 'Palavra chave do Iluminismo:', options: ['Fé', 'Razão', 'Guerra', 'Tradição'], correctAnswerIndex: 1, explanation: 'Século das Luzes/Razão.' },
    { subject: 'História', question: 'Fundador de Brasília:', options: ['Getúlio Vargas', 'JK', 'Lula', 'FHC'], correctAnswerIndex: 1, explanation: 'Juscelino Kubitschek.' },
    { subject: 'História', question: 'Ditadura Militar no Brasil durou:', options: ['10 anos', '21 anos', '30 anos', '5 anos'], correctAnswerIndex: 1, explanation: '1964 a 1985.' },
    { subject: 'História', question: 'Quem "descobriu" a América?', options: ['Cabral', 'Colombo', 'Vespucci', 'Cortés'], correctAnswerIndex: 1, explanation: 'Cristóvão Colombo em 1492.' },
    { subject: 'História', question: 'Civilização dos Andes:', options: ['Incas', 'Maias', 'Astecas', 'Tupis'], correctAnswerIndex: 0, explanation: 'Incas (Peru).' },
    { subject: 'História', question: 'Povo que construiu o Coliseu:', options: ['Gregos', 'Romanos', 'Egípcios', 'Persas'], correctAnswerIndex: 1, explanation: 'Império Romano.' },
    { subject: 'História', question: 'Presidente que suicidou-se:', options: ['JK', 'Jânio', 'Getúlio Vargas', 'Tancredo'], correctAnswerIndex: 2, explanation: 'Em 1954.' },
    { subject: 'História', question: 'Muro que dividiu a Alemanha:', options: ['Muro das Lamentações', 'Muro de Berlim', 'Grande Muralha', 'Muro de Trump'], correctAnswerIndex: 1, explanation: 'Símbolo da Guerra Fria.' },
    { subject: 'História', question: 'Quem escreveu "O Príncipe"?', options: ['Maquiavel', 'Platão', 'Aristóteles', 'Hobbes'], correctAnswerIndex: 0, explanation: 'Nicolau Maquiavel.' },
    { subject: 'História', question: 'Guerra do Paraguai envolveu:', options: ['Brasil, Argentina, Uruguai vs Paraguai', 'Brasil vs Argentina', 'Paraguai vs EUA', 'Brasil vs Bolívia'], correctAnswerIndex: 0, explanation: 'Tríplice Aliança contra o Paraguai.' },
    { subject: 'História', question: 'Primeiro homem na Lua:', options: ['Gagarin', 'Armstrong', 'Collins', 'Buzz'], correctAnswerIndex: 1, explanation: 'Neil Armstrong (1969).' },
    { subject: 'História', question: 'Ano do fim da 2ª Guerra Mundial:', options: ['1940', '1945', '1950', '1939'], correctAnswerIndex: 1, explanation: 'Terminou em 1945.' },
  ],
  'Álgebra': [
    { subject: 'Álgebra', question: 'Se x + 5 = 12, qual o valor de x?', options: ['5', '6', '7', '8'], correctAnswerIndex: 2, explanation: 'x = 12 - 5 = 7.' },
    { subject: 'Álgebra', question: 'Quanto vale y em 2y = 10?', options: ['2', '5', '8', '20'], correctAnswerIndex: 1, explanation: 'y = 10/2 = 5.' },
    { subject: 'Álgebra', question: 'Expandir (x+2)²:', options: ['x²+4', 'x²+4x+4', 'x²+2x+4', '2x+4'], correctAnswerIndex: 1, explanation: 'Quadrado do primeiro + 2x primeiro x segundo + quadrado do segundo.' },
    { subject: 'Álgebra', question: 'Fatore x² - 9:', options: ['(x-3)(x-3)', '(x+3)(x-3)', '(x+9)(x-9)', 'x(x-9)'], correctAnswerIndex: 1, explanation: 'Diferença de quadrados.' },
    { subject: 'Álgebra', question: 'Valor de x em 3x - 1 = x + 5:', options: ['2', '3', '4', '1'], correctAnswerIndex: 1, explanation: '2x = 6 -> x = 3.' },
    { subject: 'Álgebra', question: 'Se f(x) = 2x + 1, calcule f(3):', options: ['6', '7', '5', '8'], correctAnswerIndex: 1, explanation: '2(3) + 1 = 7.' },
    { subject: 'Álgebra', question: 'Resolva a inequação: x > 5, x é natural.', options: ['{0,1,2,3,4}', '{6,7,8...}', '{5,6,7...}', '{...}'], correctAnswerIndex: 1, explanation: 'Maiores que 5 (6 em diante).' },
    { subject: 'Álgebra', question: 'Coeficiente angular de y = 4x + 2:', options: ['2', '4', 'x', 'y'], correctAnswerIndex: 1, explanation: 'O valor que multiplica x (4).' },
    { subject: 'Álgebra', question: 'Raízes de x² - 5x + 6 = 0:', options: ['2 e 3', '-2 e -3', '1 e 6', '-1 e -6'], correctAnswerIndex: 0, explanation: 'Soma=5, Produto=6. Raízes 2 e 3.' },
    { subject: 'Álgebra', question: 'O que é uma função linear?', options: ['Grau 2', 'Grau 1', 'Exponencial', 'Logarítmica'], correctAnswerIndex: 1, explanation: 'f(x) = ax + b (Grau 1).' },
    { subject: 'Álgebra', question: '3x + 2y = 10 e y = x. Quanto vale x?', options: ['1', '2', '3', '4'], correctAnswerIndex: 1, explanation: '3x + 2x = 10 -> 5x=10 -> x=2.' },
    { subject: 'Álgebra', question: 'Simplifique (x^3 / x^2):', options: ['x', 'x^5', 'x^1.5', '1'], correctAnswerIndex: 0, explanation: 'Subtrai expoentes: 3-2=1 -> x.' },
    { subject: 'Álgebra', question: 'x * x * x é igual a:', options: ['3x', 'x³', 'x+3', '3^x'], correctAnswerIndex: 1, explanation: 'x ao cubo.' },
    { subject: 'Álgebra', question: 'Valor de x em x/2 = 4:', options: ['2', '6', '8', '4'], correctAnswerIndex: 2, explanation: 'x = 4 * 2 = 8.' },
    { subject: 'Álgebra', question: 'O gráfico de y=x² é uma:', options: ['Reta', 'Parábola', 'Hipérbole', 'Círculo'], correctAnswerIndex: 1, explanation: 'Função quadrática gera parábola.' },
    { subject: 'Álgebra', question: 'Discriminante (Delta) de ax²+bx+c:', options: ['b²-4ac', '2a', '-b', 'c/a'], correctAnswerIndex: 0, explanation: 'Delta = b² - 4ac.' },
    { subject: 'Álgebra', question: 'Se Delta < 0:', options: ['2 raízes reais', '1 raiz real', 'Nenhuma raiz real', '3 raízes'], correctAnswerIndex: 2, explanation: 'Não existem raízes reais.' },
    { subject: 'Álgebra', question: 'Logaritmo de 100 na base 10:', options: ['1', '2', '10', '100'], correctAnswerIndex: 1, explanation: '10² = 100.' },
    { subject: 'Álgebra', question: 'x + x =', options: ['x²', '2x', 'x', '1'], correctAnswerIndex: 1, explanation: '2x.' },
    { subject: 'Álgebra', question: 'Produto notável (a+b)(a-b):', options: ['a²-b²', 'a²+b²', 'a²-2ab+b²', 'a+b'], correctAnswerIndex: 0, explanation: 'Diferença de quadrados.' },
    { subject: 'Álgebra', question: 'Qual a declividade da reta vertical?', options: ['0', '1', 'Indefinida', '-1'], correctAnswerIndex: 2, explanation: 'Divisão por zero (tangente de 90º).' },
    { subject: 'Álgebra', question: 'Resolva |x| = 5:', options: ['5', '-5', '5 e -5', '25'], correctAnswerIndex: 2, explanation: 'Módulo pode ser 5 ou -5.' },
    { subject: 'Álgebra', question: 'Se 2^x = 8, x é:', options: ['2', '3', '4', '8'], correctAnswerIndex: 1, explanation: '2³ = 8.' },
    { subject: 'Álgebra', question: 'Matriz identidade tem:', options: ['1 na diagonal principal', '0 na diagonal principal', 'Todos 1', 'Todos 0'], correctAnswerIndex: 0, explanation: '1 na diagonal, 0 no resto.' },
    { subject: 'Álgebra', question: 'Soma de matrizes requer:', options: ['Mesma ordem', 'Mesmo determinante', 'Serem quadradas', 'Serem invertíveis'], correctAnswerIndex: 0, explanation: 'Mesmo número de linhas e colunas.' },
    { subject: 'Álgebra', question: 'Fórmula de Bhaskara serve para:', options: ['Equação de 1º grau', 'Equação de 2º grau', 'Logaritmo', 'Trigonometria'], correctAnswerIndex: 1, explanation: 'Encontrar raízes da eq. quadrática.' },
    { subject: 'Álgebra', question: 'Ponto (0,0) é a:', options: ['Origem', 'Abscissa', 'Ordenada', 'Declividade'], correctAnswerIndex: 0, explanation: 'Origem do plano cartesiano.' },
    { subject: 'Álgebra', question: 'O que é um monômio?', options: ['Soma de termos', 'Um único termo', 'Divisão', 'Igualdade'], correctAnswerIndex: 1, explanation: 'Expressão com um único termo algébrico.' },
    { subject: 'Álgebra', question: 'Grau do polinômio 3x^4 + 2x:', options: ['3', '4', '1', '2'], correctAnswerIndex: 1, explanation: 'O maior expoente é 4.' },
    { subject: 'Álgebra', question: 'Inverso de adicionar 5:', options: ['Multiplicar por 5', 'Subtrair 5', 'Dividir por 5', 'Somar -1'], correctAnswerIndex: 1, explanation: 'Operação inversa da soma é subtração.' }
  ],
  'Química': [
    { subject: 'Química', question: 'O átomo é formado por:', options: ['Prótons e Neutrons', 'Prótons, Neutrons e Elétrons', 'Apenas Elétrons', 'Células'], correctAnswerIndex: 1, explanation: 'Núcleo e eletrosfera.' },
    { subject: 'Química', question: 'Qual o principal componente do gás natural?', options: ['Metano', 'Etano', 'Butano', 'Propano'], correctAnswerIndex: 0, explanation: 'Metano (CH4) compõe cerca de 70-90%.' },
    { subject: 'Química', question: 'O que é uma reação exotérmica?', options: ['Absorve calor', 'Libera calor', 'Não altera calor', 'Cria matéria'], correctAnswerIndex: 1, explanation: 'Libera energia sob forma de calor.' },
    { subject: 'Química', question: 'Ligação entre metal e ametal:', options: ['Covalente', 'Iônica', 'Metálica', 'De Hidrogênio'], correctAnswerIndex: 1, explanation: 'Transferência de elétrons.' },
    { subject: 'Química', question: 'Elemento mais abundante no universo:', options: ['Oxigênio', 'Hidrogênio', 'Hélio', 'Carbono'], correctAnswerIndex: 1, explanation: 'Hidrogênio (~75%).' },
    { subject: 'Química', question: 'Massa atômica do Carbono:', options: ['1', '12', '14', '16'], correctAnswerIndex: 1, explanation: 'Padrão C-12.' },
    { subject: 'Química', question: 'O que define um elemento químico?', options: ['Massa', 'Nº de Neutrons', 'Nº de Prótons', 'Nº de Elétrons'], correctAnswerIndex: 2, explanation: 'Número atômico (Z).' },
    { subject: 'Química', question: 'Mistura heterogênea de água e óleo:', options: ['Solução', 'Coloide', 'Bifásica', 'Homoogênea'], correctAnswerIndex: 2, explanation: 'Apresenta duas fases visíveis.' },
    { subject: 'Química', question: 'Função orgânica -OH ligada a carbono saturado:', options: ['Fenol', 'Álcool', 'Aldeído', 'Éter'], correctAnswerIndex: 1, explanation: 'Grupo Hidroxila.' },
    { subject: 'Química', question: 'Gás ozônio protege contra:', options: ['Chuva ácida', 'Raios UV', 'Efeito estufa', 'Aquecimento'], correctAnswerIndex: 1, explanation: 'Camada de Ozônio (O3).' },
    { subject: 'Química', question: 'Estado físico do Ferro a 50ºC:', options: ['Líquido', 'Sólido', 'Gasoso', 'Plasma'], correctAnswerIndex: 1, explanation: 'Ponto de fusão é ~1538ºC.' },
    { subject: 'Química', question: 'Partícula do átomo com carga positiva:', options: ['Eletron', 'Neutron', 'Proton', 'Fóton'], correctAnswerIndex: 2, explanation: 'Prótons ficam no núcleo.' },
    { subject: 'Química', question: 'Qual o pH do suco gástrico?', options: ['1-3', '7', '8-10', '13-14'], correctAnswerIndex: 0, explanation: 'Muito ácido para digestão.' },
    { subject: 'Química', question: 'Modelo atômico conhecido como "bola de bilhar":', options: ['Thomson', 'Rutherford', 'Dalton', 'Bohr'], correctAnswerIndex: 2, explanation: 'Dalton visualizava como esfera maciça.' },
    { subject: 'Química', question: 'Símbolo do Sódio:', options: ['S', 'So', 'Na', 'Sn'], correctAnswerIndex: 2, explanation: 'Natrium.' },
    { subject: 'Química', question: 'Ouro 18K é uma:', options: ['Substância pura', 'Liga metálica', 'Substância composta', 'Ametia'], correctAnswerIndex: 1, explanation: 'Mistura de ouro e outros metais.' },
    { subject: 'Química', question: 'Produto da combustão completa de hidrocarbonetos:', options: ['CO + H2O', 'CO2 + H2O', 'C + H2', 'O2 + H2'], correctAnswerIndex: 1, explanation: 'Dióxido de carbono e água.' },
    { subject: 'Química', question: 'O que é um isótopo?', options: ['Mesma massa', 'Mesmo nº de prótons', 'Mesmo nº de neutrons', 'Mesma densidade'], correctAnswerIndex: 1, explanation: 'Varia apenas o nº de neutrons.' },
    { subject: 'Química', question: 'Unidade de massa atômica:', options: ['g', 'kg', 'u', 'mol'], correctAnswerIndex: 2, explanation: 'Símbolo u.' },
    { subject: 'Química', question: 'Símbolo do Ferro:', options: ['F', 'Fe', 'Fr', 'Fi'], correctAnswerIndex: 1, explanation: 'Ferrum.' },
    { subject: 'Química', question: 'Uma solução saturada atingiu o:', options: ['Ponto de fusão', 'Limite de solubilidade', 'Equilíbrio térmico', 'Vácuo'], correctAnswerIndex: 1, explanation: 'Não consegue dissolver mais soluto.' }
  ],
  'Inglês': [
    { subject: 'Inglês', question: 'Oposto de "Big":', options: ['Large', 'Huge', 'Small', 'Grand'], correctAnswerIndex: 2, explanation: 'Big (Grande) x Small (Pequeno).' },
    { subject: 'Inglês', question: 'Significado de "Actually":', options: ['Atualmente', 'Na verdade', 'Frequentemente', 'Raramente'], correctAnswerIndex: 1, explanation: 'Falso cognato: Actually = Na verdade.' },
    { subject: 'Inglês', question: '"I have ___ a movie":', options: ['see', 'saw', 'seen', 'seeing'], correctAnswerIndex: 2, explanation: 'Present Perfect: have + participle.' },
    { subject: 'Inglês', question: 'Significado de "Library":', options: ['Livraria', 'Biblioteca', 'Loja', 'Escola'], correctAnswerIndex: 1, explanation: 'Falso cognato: Library = Biblioteca.' },
    { subject: 'Inglês', question: '"If I ___ you, I would go":', options: ['am', 'was', 'were', 'be'], correctAnswerIndex: 2, explanation: 'Second Conditional usa "were" para todas as pessoas.' },
    { subject: 'Inglês', question: 'Tradução de "Wait":', options: ['Pesar', 'Esperar', 'Trabalhar', 'Sair'], correctAnswerIndex: 1, explanation: 'Wait = Esperar.' },
    { subject: 'Inglês', question: 'Cor "Purple":', options: ['Rosa', 'Roxo', 'Preto', 'Branco'], correctAnswerIndex: 1, explanation: 'Purple = Roxo.' },
    { subject: 'Inglês', question: 'Significado de "Mayor":', options: ['Maior', 'Prefeito', 'Melhor', 'Militar'], correctAnswerIndex: 1, explanation: 'Mayor = Prefeito.' },
    { subject: 'Inglês', question: 'Verbo "To Read" no passado:', options: ['Readed', 'Read (pronuncia-se "red")', 'Rode', 'Reading'], correctAnswerIndex: 1, explanation: 'Escrita igual, pronúncia muda.' },
    { subject: 'Inglês', question: 'Qual o tempo de "I am working"?', options: ['Simple Present', 'Present Continuous', 'Present Perfect', 'Future'], correctAnswerIndex: 1, explanation: 'Ação em progresso no presente.' },
    { subject: 'Inglês', question: 'Significado de "Parents":', options: ['Parentes', 'Pais', 'Padres', 'Parceiros'], correctAnswerIndex: 1, explanation: 'Falso cognato: Parents = Pais.' },
    { subject: 'Inglês', question: '"Apple" é uma:', options: ['Animal', 'Fruit', 'Country', 'Object'], correctAnswerIndex: 1, explanation: 'Apple = Maçã.' },
    { subject: 'Inglês', question: 'O que é um "Cognate"?', options: ['Palavra difícil', 'Palavra com origem comum e sentido igual', 'Gíria', 'Palavra proibida'], correctAnswerIndex: 1, explanation: 'Ex: Radio, Television.' },
    { subject: 'Inglês', question: '"There ___ a cat on the mat":', options: ['is', 'are', 'am', 'be'], correctAnswerIndex: 0, explanation: 'There is (Singular).' },
    { subject: 'Inglês', question: 'Significado de "Often":', options: ['Nunca', 'Frequentemente', 'Sempre', 'Talvez'], correctAnswerIndex: 1, explanation: 'Often = Com frequência.' },
    { subject: 'Inglês', question: 'Passado de "Write":', options: ['Writed', 'Written', 'Wrote', 'Writing'], correctAnswerIndex: 2, explanation: 'Write -> Wrote.' },
    { subject: 'Inglês', question: '"Will" indica:', options: ['Passado', 'Futuro', 'Possibilidade', 'Obrigação'], correctAnswerIndex: 1, explanation: 'Auxiliar do futuro.' },
    { subject: 'Inglês', question: 'Significado de "Bridge":', options: ['Prédio', 'Ponte', 'Rua', 'Carro'], correctAnswerIndex: 1, explanation: 'Bridge = Ponte.' },
    { subject: 'Inglês', question: 'Plural de "Child":', options: ['Childs', 'Children', 'Childes', 'Childers'], correctAnswerIndex: 1, explanation: 'Plural irregular.' },
    { subject: 'Inglês', question: 'Expressão "What\'s up?":', options: ['O que é isso?', 'E aí?', 'Onde está?', 'Qual seu nome?'], correctAnswerIndex: 1, explanation: 'Gíria informal de saudação.' },
    { subject: 'Inglês', question: '"Can" indica:', options: ['Desejo', 'Habilidade/Possibilidade', 'Passado', 'Dúvida'], correctAnswerIndex: 1, explanation: 'Pode/Consegue.' }
  ],
  'Geometria': [
    { subject: 'Geometria', question: 'Teorema de Pitágoras:', options: ['a=b+c', 'a²=b²+c²', 'a³=b³+c³', 'a=b*c'], correctAnswerIndex: 1, explanation: 'Soma dos quadrados dos catetos.' },
    { subject: 'Geometria', question: 'Soma dos ângulos internos de um triângulo:', options: ['90º', '180º', '270º', '360º'], correctAnswerIndex: 1, explanation: 'Sempre 180 graus.' },
    { subject: 'Geometria', question: 'Área do círculo:', options: ['2πr', 'πr²', 'πd', 'r²'], correctAnswerIndex: 1, explanation: 'Pi vezes raio ao quadrado.' },
    { subject: 'Geometria', question: 'O que é um apótema?', options: ['Lado do polígono', 'Raio do círculo inscrito', 'Diagonal', 'Ângulo interno'], correctAnswerIndex: 1, explanation: 'Distância do centro ao meio de um lado.' },
    { subject: 'Geometria', question: 'Volume da esfera:', options: ['πr²', '4/3 πr³', '2πr', 'l³'], correctAnswerIndex: 1, explanation: 'Fórmula clássica do volume.' },
    { subject: 'Geometria', question: 'Soma dos ângulos externos de qualquer polígono convexo:', options: ['180º', '360º', '540º', 'Depende do nº de lados'], correctAnswerIndex: 1, explanation: 'Sempre 360 graus.' },
    { subject: 'Geometria', question: 'Um polígono de 12 lados é um:', options: ['Decágono', 'Dodecágono', 'Icoságono', 'Eneágono'], correctAnswerIndex: 1, explanation: 'Dode (2) + deca (10).' },
    { subject: 'Geometria', question: 'Ângulos suplementares somam:', options: ['90º', '180º', '360º', '270º'], correctAnswerIndex: 1, explanation: 'Complementares somam 90, suplementares 180.' },
    { subject: 'Geometria', question: 'Área de um trapézio:', options: ['(B+b)*h/2', 'B*h', 'L²', 'B+b+h'], correctAnswerIndex: 0, explanation: '(Base maior + base menor) * altura / 2.' },
    { subject: 'Geometria', question: 'O que é uma reta secante?', options: ['Toca em 1 ponto', 'Toca em 2 pontos', 'Não toca', 'Passa pelo centro'], correctAnswerIndex: 1, explanation: 'Corta a curva em dois pontos.' },
    { subject: 'Geometria', question: 'Diagonal de um quadrado de lado L:', options: ['L√2', 'L√3', '2L', 'L²/2'], correctAnswerIndex: 0, explanation: 'Derivado de Pitágoras.' },
    { subject: 'Geometria', question: 'Quantos graus tem o ângulo raso?', options: ['90º', '180º', '360º', '0º'], correctAnswerIndex: 1, explanation: 'Meia volta.' },
    { subject: 'Geometria', question: 'Um tetraedro tem quantas faces?', options: ['4', '6', '8', '12'], correctAnswerIndex: 0, explanation: 'Pirâmide de base triangular (4 faces).' },
    { subject: 'Geometria', question: 'Valor do seno de 90º:', options: ['0', '1', '0.5', '√2/2'], correctAnswerIndex: 1, explanation: 'Máximo valor do seno.' },
    { subject: 'Geometria', question: 'O que são retas paralelas?', options: ['Se cruzam em 90º', 'Nunca se cruzam', 'Se cruzam em 1 ponto', 'São iguais'], correctAnswerIndex: 1, explanation: 'Mantêm a mesma distância.' },
    { subject: 'Geometria', question: 'Área lateral de um cilindro:', options: ['πr²h', '2πrh', 'πr²', '2πr'], correctAnswerIndex: 1, explanation: 'Perímetro da base vezes altura.' },
    { subject: 'Geometria', question: 'Um ângulo de 45º é:', options: ['Reto', 'Obtuso', 'Agudo', 'Raso'], correctAnswerIndex: 2, explanation: 'Menor que 90º.' },
    { subject: 'Geometria', question: 'Quantas diagonais tem um triângulo?', options: ['0', '1', '3', '2'], correctAnswerIndex: 0, explanation: 'Triângulo não possui diagonais internas.' },
    { subject: 'Geometria', question: 'Fórmula de Euler para poliedros:', options: ['V+F=E+2', 'V+E=F+2', 'F+E=V+2', 'V+F+E=2'], correctAnswerIndex: 0, explanation: 'Vértices + Faces = Arestas + 2.' },
    { subject: 'Geometria', question: 'O que é o incentro?', options: ['Encontro das medianas', 'Encontro das bissetrizes', 'Encontro das alturas', 'Centro das arestas'], correctAnswerIndex: 1, explanation: 'Centro do círculo inscrito.' },
    { subject: 'Geometria', question: 'Área do losango:', options: ['L²', 'D*d/2', 'B*h', '2*pi*r'], correctAnswerIndex: 1, explanation: 'Diagonal maior vezes menor sobre 2.' }
    ,
    { subject: 'Geometria', question: 'Quantas faces tem um cubo?', options: ['4', '6', '8', '12'], correctAnswerIndex: 1, explanation: '6 faces.' },
    { subject: 'Geometria', question: 'Linha que divide o círculo ao meio:', options: ['Raio', 'Diâmetro', 'Tangente', 'Secante'], correctAnswerIndex: 1, explanation: 'Diâmetro passa pelo centro.' }
  ],
  'Biologia': [
    { subject: 'Biologia', question: 'Maior órgão do corpo:', options: ['Fígado', 'Coração', 'Pele', 'Pulmão'], correctAnswerIndex: 2, explanation: 'A pele.' },
    { subject: 'Biologia', question: 'O que é a hemoglobina?', options: ['Proteína que transporta O2', 'Tipo de açúcar', 'Célula de defesa', 'Hormônio'], correctAnswerIndex: 0, explanation: 'Presente nas hemácias.' },
    { subject: 'Biologia', question: 'Função do Ribossomo:', options: ['Produzir energia', 'Sintetizar proteínas', 'Digestão', 'Divisão celular'], correctAnswerIndex: 1, explanation: 'Fábrica de proteínas.' },
    { subject: 'Biologia', question: 'Organismo autótrofo:', options: ['Come outros seres', 'Produz o próprio alimento', 'Vive no lixo', 'É parasita'], correctAnswerIndex: 1, explanation: 'Como as plantas.' },
    { subject: 'Biologia', question: 'O que é homeostase?', options: ['Equilíbrio interno', 'Tipo de doença', 'Crescimento', 'Morte celular'], correctAnswerIndex: 0, explanation: 'Manutenção das condições constantes.' },
    { subject: 'Biologia', question: 'Principal osso da coxa:', options: ['Tíbia', 'Fêmur', 'Rádio', 'Úmero'], correctAnswerIndex: 1, explanation: 'Maior osso do corpo.' },
    { subject: 'Biologia', question: 'O que são enzimas?', options: ['Gorduras', 'Catalisadores biológicos (proteínas)', 'Açúcares', 'Vitaminas'], correctAnswerIndex: 1, explanation: 'Aceleram reações químicas.' },
    { subject: 'Biologia', question: 'Parte da planta que faz fotossíntese (geralmente):', options: ['Raiz', 'Caule', 'Folha', 'Semente'], correctAnswerIndex: 2, explanation: 'Ricas em clorofila.' },
    { subject: 'Biologia', question: 'O que é o nicho ecológico?', options: ['Lugar onde mora', 'Papel/Função na comunidade', 'Tipo de reprodução', 'Tamanho do bicho'], correctAnswerIndex: 1, explanation: 'O "trabalho" do ser no ambiente.' },
    { subject: 'Biologia', question: 'Vírus são seres:', options: ['Procariontes', 'Eucariontes', 'Acelulares', 'Unicelulares'], correctAnswerIndex: 2, explanation: 'Não possuem célula própria.' },
    { subject: 'Biologia', question: 'Processo de divisão para gametas:', options: ['Mitose', 'Meiose', 'Bifurcação', 'Clonagem'], correctAnswerIndex: 1, explanation: 'Reduz o nº de cromossomos à metade.' },
    { subject: 'Biologia', question: 'O que é a seleção natural?', options: ['Sobrevivência do mais forte/apto', 'Uso e desuso', 'Mutação proposital', 'Vontade divina'], correctAnswerIndex: 0, explanation: 'Teoria de Darwin.' },
    { subject: 'Biologia', question: 'Vetor da Dengue:', options: ['Barata', 'Aedes aegypti', 'Rato', 'Pulga'], correctAnswerIndex: 1, explanation: 'Mosquito.' },
    { subject: 'Biologia', question: 'Base nitrogenada exclusivado DNA:', options: ['Uracila', 'Timina', 'Adenina', 'Guanina'], correctAnswerIndex: 1, explanation: 'RNA tem Uracila no lugar.' },
    { subject: 'Biologia', question: 'Hormônio que regula o açúcar:', options: ['Adrenalina', 'Insulina', 'Melatonina', 'Testosterona'], correctAnswerIndex: 1, explanation: 'Produzido no pâncreas.' },
    { subject: 'Biologia', question: 'Zoologia estuda os:', options: ['Plantas', 'Animais', 'Fungos', 'Vírus'], correctAnswerIndex: 1, explanation: 'Reino Metazoa.' },
    { subject: 'Biologia', question: 'O que é a clorofila?', options: ['Pigmento verde', 'Tipo de flor', 'Raiz', 'Inseto'], correctAnswerIndex: 0, explanation: 'Captura energia luminosa.' },
    { subject: 'Biologia', question: 'Respiração dos peixes:', options: ['Pulmonar', 'Branquial', 'Cutânea', 'Traqueal'], correctAnswerIndex: 1, explanation: 'Guelras/Brânquias.' },
    { subject: 'Biologia', question: 'Unidade funcional do rim:', options: ['Neurônio', 'Néfron', 'Alvéolo', 'Miócito'], correctAnswerIndex: 1, explanation: 'Filtragem do sangue.' },
    { subject: 'Biologia', question: 'O que é a biosfera?', options: ['Camada de ar', 'Conjunto de todos os ecossistemas', 'Só os oceanos', 'Apenas florestas'], correctAnswerIndex: 1, explanation: 'Esfera da vida.' },
    { subject: 'Biologia', question: 'Simbiose é uma relação:', options: ['Harmônica/Benéfica', 'Desarmônica', 'Indiferente', 'De guerra'], correctAnswerIndex: 0, explanation: 'Ajuda mútua.' }
  ],
  'Geografia': [
    { subject: 'Geografia', question: 'O que é relevo?', options: ['Clima', 'Formas da terra', 'Rios', 'Vegetação'], correctAnswerIndex: 1, explanation: 'Montanhas, planícies, etc.' },
    { subject: 'Geografia', question: 'Clima predominante no Brasil:', options: ['Polar', 'Tropical', 'Temperado', 'Desértico'], correctAnswerIndex: 1, explanation: 'Devido à localização entre os trópicos.' },
    { subject: 'Geografia', question: 'O que é o efeito estufa?', options: ['Aquecimento natural da Terra', 'Resfriamento', 'Chuva de granizo', 'Fim do mundo'], correctAnswerIndex: 0, explanation: 'Fenômeno natural necessário, mas intensificado pelo homem.' },
    { subject: 'Geografia', question: 'Vegetação do Nordeste brasileiro:', options: ['Pampas', 'Caatinga', 'Cerrado', 'Pantanal'], correctAnswerIndex: 1, explanation: 'Adaptada à aridez.' },
    { subject: 'Geografia', question: 'O que é a densidade demográfica?', options: ['População total', 'Habitantes por km²', 'Número de idosos', 'Riqueza do país'], correctAnswerIndex: 1, explanation: 'Relação entre habitantes e área.' },
    { subject: 'Geografia', question: 'Canal que liga Atlântico e Pacífico:', options: ['Canal de Suez', 'Canal do Panamá', 'Canal da Mancha', 'Rio Amazonas'], correctAnswerIndex: 1, explanation: 'No istmo do Panamá.' },
    { subject: 'Geografia', question: 'Principal fonte de energia da China:', options: ['Nuclear', 'Carvão Mineral', 'Solar', 'Hidrelétrica'], correctAnswerIndex: 1, explanation: 'Ainda muito dependente do carvão.' },
    { subject: 'Geografia', question: 'País que saiu da União Europeia (Brexit):', options: ['França', 'Reino Unido', 'Alemanha', 'Grécia'], correctAnswerIndex: 1, explanation: 'Processo concluído em 2020.' },
    { subject: 'Geografia', question: 'O que é o PIB?', options: ['Índice de inflação', 'Produto Interno Bruto', 'Poder de Compra', 'Imposto'], correctAnswerIndex: 1, explanation: 'Soma de riquezas produzidas.' },
    { subject: 'Geografia', question: 'Montanha mais alta do mundo:', options: ['K2', 'Everest', 'Aconcágua', 'Mont Blanc'], correctAnswerIndex: 1, explanation: 'Localizada no Himalaia.' },
    { subject: 'Geografia', question: 'O que é a linha de Greenwich?', options: ['Divide Norte/Sul', 'Meridiano 0º (Divide Leste/Oeste)', 'Linha do frio', 'Fronteira'], correctAnswerIndex: 1, explanation: 'Referência para fusos horários.' },
    { subject: 'Geografia', question: 'Fenômeno El Niño ocorre no:', options: ['Atlântico', 'Pacífico', 'Índico', 'Ártico'], correctAnswerIndex: 1, explanation: 'Aquecimento das águas do Pacífico.' },
    { subject: 'Geografia', question: 'Estado brasileiro com maior população:', options: ['Rio de Janeiro', 'São Paulo', 'Minas Gerais', 'Bahia'], correctAnswerIndex: 1, explanation: 'SP é o mais populoso.' },
    { subject: 'Geografia', question: 'O que é gentrificação?', options: ['Plantio de árvores', 'Valorização imobiliária que expulsa pobres', 'Aumento de indústrias', 'Migração'], correctAnswerIndex: 1, explanation: 'Transformação de áreas urbanas degradadas em nobres.' },
    { subject: 'Geografia', question: 'Principal bacia hidrográfica do mundo:', options: ['Do Prata', 'Amazônica', 'Do Nilo', 'Do Congo'], correctAnswerIndex: 1, explanation: 'Maior volume de água doce.' },
    { subject: 'Geografia', question: 'O que causa as estações do ano?', options: ['Rotação', 'Translação + inclinação do eixo', 'Distância do Sol', 'Aquecimento Global'], correctAnswerIndex: 1, explanation: 'Combinação do movimento orbital e inclinação terrestre.' },
    { subject: 'Geografia', question: 'País com maior população do mundo:', options: ['China', 'Índia', 'EUA', 'Indonésia'], correctAnswerIndex: 1, explanation: 'Índia ultrapassou a China recentemente.' },
    { subject: 'Geografia', question: 'O que é um bioma?', options: ['Tipo de solo', 'Grande ecossistema com fauna/flora típicas', 'Pequeno jardim', 'Cadeia alimentar'], correctAnswerIndex: 1, explanation: 'Ex: Amazônia, Savana.' },
    { subject: 'Geografia', question: 'Qual continente é o berço da humanidade?', options: ['Europa', 'Ásia', 'África', 'América'], correctAnswerIndex: 2, explanation: 'Surgimento dos primeiros hominídeos.' },
    { subject: 'Geografia', question: 'O que é a desertificação?', options: ['Aumento de areia na praia', 'Degradação da terra em zonas áridas', 'Frio extremo', 'Enchente'], correctAnswerIndex: 1, explanation: 'Perda de produtividade do solo.' },
    { subject: 'Geografia', question: 'A camada de ozônio fica na:', options: ['Troposfera', 'Estratosfera', 'Mesosfera', 'Exosfera'], correctAnswerIndex: 1, explanation: 'Região da atmosfera rica em O3.' }
  ],
  'Literatura': [
    { subject: 'Literatura', question: 'Gênero Dramático é para:', options: ['Ler', 'Encenar', 'Cantar', 'Dança'], correctAnswerIndex: 1, explanation: 'Teatro.' },
    { subject: 'Literatura', question: 'O que é uma estrofe?', options: ['Um verso', 'Conjunto de versos', 'Uma rima', 'Um título'], correctAnswerIndex: 1, explanation: 'Agrupamento de linhas em um poema.' },
    { subject: 'Literatura', question: 'Principal autor do Realismo no Brasil:', options: ['José de Alencar', 'Machado de Assis', 'Castro Alves', 'Aluísio Azevedo'], correctAnswerIndex: 1, explanation: 'Autor de "Memórias Póstumas".' },
    { subject: 'Literatura', question: 'Obra marco do Modernismo em 1922:', options: ['Os Lusíadas', 'Pauliceia Desvairada', 'Iracema', 'Dom Casmurro'], correctAnswerIndex: 1, explanation: 'De Mário de Andrade.' },
    { subject: 'Literatura', question: 'O que é personificação (prosopopeia)?', options: ['Atribuir qualidades humanas a seres inanimados', 'Exagerar', 'Comparar', 'Trocar sons'], correctAnswerIndex: 0, explanation: 'Ex: "O vento sussurrou".' },
    { subject: 'Literatura', question: 'Autor de "Vidas Secas":', options: ['Jorge Amado', 'Graciliano Ramos', 'Clarice Lispector', 'Guimarães Rosa'], correctAnswerIndex: 1, explanation: 'Obra sobre a seca no Nordeste.' },
    { subject: 'Literatura', question: 'O que é um soneto?', options: ['Poema de 10 versos', 'Poema de 14 versos (2 quartetos, 2 tercetos)', 'Poema livre', 'Uma música'], correctAnswerIndex: 1, explanation: 'Forma clássica fixa.' },
    { subject: 'Literatura', question: 'Movimento que buscava a perfeição formal:', options: ['Romantismo', 'Parnasianismo', 'Naturalismo', 'Barroco'], correctAnswerIndex: 1, explanation: 'Arte pela arte.' },
    { subject: 'Literatura', question: 'Líder do Arcadismo no Brasil:', options: ['Tomás Antônio Gonzaga', 'Gregório de Matos', 'Cláudio Manuel da Costa', 'Ambos A e C'], correctAnswerIndex: 3, explanation: 'Poetas da Inconfidência Mineira.' },
    { subject: 'Literatura', question: 'O que é paradoxo?', options: ['Ideias opostas que se excluem logicamente', 'Repetição de voga', 'Aumento de sentido', 'Dúvida'], correctAnswerIndex: 0, explanation: 'Ex: "Amor é fogo que arde sem se ver".' },
    { subject: 'Literatura', question: 'Autor de "A Hora da Estrela":', options: ['Machado', 'Clarice Lispector', 'Cecília Meireles', 'Lygia Fagundes Telles'], correctAnswerIndex: 1, explanation: 'Último livro publicado em vida pela autora.' },
    { subject: 'Literatura', question: 'O que caracteriza o Romantismo?', options: ['Razão e objetividade', 'Subjetividade e sentimentalismo', 'Foco na ciência', 'Linguagem difícil'], correctAnswerIndex: 1, explanation: 'Foco no "eu" e nas emoções.' },
    { subject: 'Literatura', question: 'Quem é o "Boca do Inferno"?', options: ['Machado de Assis', 'Gregório de Matos', 'Padre Antônio Vieira', 'Camões'], correctAnswerIndex: 1, explanation: 'Devido à sua poesia satírica ácida.' },
    { subject: 'Literatura', question: 'O que é um narrador onisciente?', options: ['Sabe tudo sobre a história e pensamentos', 'É um personagem', 'Só observa de fora', 'Mente sempre'], correctAnswerIndex: 0, explanation: 'Conhece até o íntimo dos personagens.' },
    { subject: 'Literatura', question: 'Obra principal de Guimarães Rosa:', options: ['Grande Sertão: Veredas', 'O Quinze', 'A Bagaceira', 'Auto da Compadecida'], correctAnswerIndex: 0, explanation: 'Obra monumental da 3ª fase modernista.' },
    { subject: 'Literatura', question: 'O que é intertextualidade?', options: ['Diálogo entre dois ou mais textos', 'Erro de escrita', 'Tradução', 'Poema sem rima'], correctAnswerIndex: 0, explanation: 'Quando um texto cita ou referencia outro.' },
    { subject: 'Literatura', question: 'Autor de "O Guarani":', options: ['Machado', 'José de Alencar', 'Gonçalves Dias', 'Aluísio'], correctAnswerIndex: 1, explanation: 'Romantismo Indianista.' },
    { subject: 'Literatura', question: 'O que é metalinguagem?', options: ['Linguagem sobre a própria linguagem', 'Linguagem técnica', 'Linguagem obscena', 'Linguagem estrangeira'], correctAnswerIndex: 0, explanation: 'O filme que fala sobre cinema, o poema sobre poesia.' },
    { subject: 'Literatura', question: 'Poeta de "Morte e Vida Severina":', options: ['Carlos Drummond', 'João Cabral de Melo Neto', 'Vinicius de Moraes', 'Olavo Bilac'], correctAnswerIndex: 1, explanation: 'Poesia substantiva e rigorosa.' },
    { subject: 'Literatura', question: 'O que é farsa (no teatro)?', options: ['Tragédia grega', 'Comédia curta e caricata', 'Drama pesado', 'Ópera'], correctAnswerIndex: 1, explanation: 'Ex: Auto da Barca do Inferno (partes).' },
    { subject: 'Literatura', question: 'Autor de "O Cortiço":', options: ['Aluísio Azevedo', 'Adolfo Caminha', 'Raul Pompeia', 'Lima Barreto'], correctAnswerIndex: 0, explanation: 'Clássico do Naturalismo.' }
  ],
  'Gramática': [
    { subject: 'Gramática', question: 'Substantivo que varia em gênero:', options: ['Mesa', 'Cadeira', 'Menino', 'Lápis'], correctAnswerIndex: 2, explanation: 'Menino/Menina.' },
    { subject: 'Gramática', question: 'Verbo de 1ª conjugação termina em:', options: ['ER', 'IR', 'OR', 'AR'], correctAnswerIndex: 3, explanation: 'Amar, Cantar.' },
    { subject: 'Gramática', question: 'Pronome pessoal do caso reto:', options: ['Me', 'Te', 'Eu', 'Se'], correctAnswerIndex: 2, explanation: 'Eu, Tu, Ele...' },
    { subject: 'Gramática', question: 'Adjetivo pátrio de quem nasce no estado do Rio:', options: ['Carioca', 'Fluminense', 'Rio-grandense', 'Baiano'], correctAnswerIndex: 1, explanation: 'Fluminense (Carioca é da cidade).' },
    { subject: 'Gramática', question: 'Coletivo de lobos:', options: ['Alcateia', 'Matilha', 'Bando', 'Cardume'], correctAnswerIndex: 0, explanation: 'Alcateia.' },
    { subject: 'Gramática', question: 'Sinônimo de "Bonito":', options: ['Feio', 'Horrível', 'Belo', 'Grande'], correctAnswerIndex: 2, explanation: 'Belo.' },
    { subject: 'Gramática', question: 'Antônimo de "Alto":', options: ['Baixo', 'Largo', 'Pequeno', 'Gordo'], correctAnswerIndex: 0, explanation: 'Baixo.' },
    { subject: 'Gramática', question: 'Silaba tônica de "Café":', options: ['Ca', 'Fé', 'Nenhuma', 'Ambas'], correctAnswerIndex: 1, explanation: 'Oxítona.' },
    { subject: 'Gramática', question: 'Uso dos "porquês" (final de frase):', options: ['Porque', 'Por que', 'Porquê', 'Por quê'], correctAnswerIndex: 3, explanation: 'Separado e com acento.' },
    { subject: 'Gramática', question: 'Vírgula serve para:', options: ['Terminar frase', 'Omitir letra', 'Pausar/Separar', 'Gritar'], correctAnswerIndex: 2, explanation: 'Pausa ou separação de termos.' },
    { subject: 'Gramática', question: 'O que é uma próclise?', options: ['Pronome antes do verbo', 'Pronome depois do verbo', 'Pronome no meio do verbo', 'Erro de escrita'], correctAnswerIndex: 0, explanation: 'Ex: "Não me diga".' },
    { subject: 'Gramática', question: 'A palavra "táxi" é acentuada pois é:', options: ['Oxítona', 'Paroxítona terminada em i', 'Proparoxítona', 'Monossílaba'], correctAnswerIndex: 1, explanation: 'Regra das paroxítonas.' },
    { subject: 'Gramática', question: 'Plural de "pau-brasil":', options: ['paus-brasil', 'paus-brasileis', 'pau-brasis', 'pau-brasiles'], correctAnswerIndex: 0, explanation: 'Apenas o primeiro elemento varia (substantivo + substantivo especificado).' },
    { subject: 'Gramática', question: 'O que é um advérbio?', options: ['Nomeia seres', 'Modifica o verbo, adjetivo ou outro advérbio', 'Indica ação', 'Liga frases'], correctAnswerIndex: 1, explanation: 'Indica circunstância (tempo, modo, etc).' },
    { subject: 'Gramática', question: 'Assinale a alternativa correta quanto à regência:', options: ['Assisti o filme', 'Assisti ao filme', 'Assisti no filme', 'Assisti o longa'], correctAnswerIndex: 1, explanation: 'Verbo assistir (ver) exige a preposição "a".' },
    { subject: 'Gramática', question: 'O que é um hiato?', options: ['Duas vogais na mesma sílaba', 'Duas vogais em sílabas separadas', 'Duas consoantes juntas', 'Fim do texto'], correctAnswerIndex: 1, explanation: 'Ex: Sa-ú-de.' },
    { subject: 'Gramática', question: 'Voz passiva de "Eu li o livro":', options: ['O livro foi lido por mim', 'Eu tinha lido o livro', 'O livro lia-se', 'Lra-se o livro'], correctAnswerIndex: 0, explanation: 'O objeto direto vira sujeito paciente.' },
    { subject: 'Gramática', question: 'Conjunção "embora" indica:', options: ['Causa', 'Concessão', 'Tempo', 'Finalidade'], correctAnswerIndex: 1, explanation: 'Indica uma oposição que não impede a ação principal.' },
    { subject: 'Gramática', question: 'O que é um substantivo abstrato?', options: ['Nomeia objetos', 'Nomeia sentimentos, ações ou estados', 'Nomeia lugares', 'Nomeia pessoas'], correctAnswerIndex: 1, explanation: 'Dependem de outro ser para existir (ex: amor).' },
    { subject: 'Gramática', question: 'Diferença entre "a gente" e "nós":', options: ['Sentido diferente', 'Registro coloquial vs formal', 'Tempo verbal', 'Não há diferença'], correctAnswerIndex: 1, explanation: '"A gente" é coloquial e pede verbo no singular.' },
    { subject: 'Gramática', question: 'O que é elipse na gramática?', options: ['Omissão de um termo subentendido', 'Repetição', 'Exagero', 'Comparação'], correctAnswerIndex: 0, explanation: 'Ex: (Nós) fomos ao cinema.' },
    { subject: 'Gramática', question: 'Forma correta: "fazem cinco anos" ou "faz cinco anos"?', options: ['Fazem', 'Faz', 'Ambos', 'Nenhum'], correctAnswerIndex: 1, explanation: 'Verbo fazer indicando tempo decorrido é impessoal (sempre singular).' },
    { subject: 'Gramática', question: 'O que é a crase?', options: ['Acento agudo', 'Fusão de duas vogais iguais (a+a)', 'Pausa na fala', 'Acento tônico'], correctAnswerIndex: 1, explanation: 'Preposição "a" + Artigo "a".' },
    { subject: 'Gramática', question: 'Qual o infinitivo de "puseram"?', options: ['Puser', 'Pôr', 'Posar', 'Pousar'], correctAnswerIndex: 1, explanation: 'Verbo Pôr.' },
    { subject: 'Gramática', question: 'O que é uma oração coordenada?', options: ['Dependende da principal', 'Independente sintaticamente', 'Sem verbo', 'Frase curta'], correctAnswerIndex: 1, explanation: 'Possuem sentido completo sozinhas.' },
    { subject: 'Gramática', question: 'Significado de "ratificar":', options: ['Mudar', 'Confirmar', 'Corrigir', 'Anular'], correctAnswerIndex: 1, explanation: 'Ratificar = Confirmar. Corrigir = Retificar.' },
    { subject: 'Gramática', question: 'Plural de "mal":', options: ['Maus', 'Males', 'Mals', 'Mal'], correctAnswerIndex: 1, explanation: 'Mal (substantivo) -> Males. Mal (advérbio) não varia.' },
    { subject: 'Gramática', question: 'Dígrafo "rr" se separa na sílaba?', options: ['Sim', 'Não', 'Opcional', 'Nunca'], correctAnswerIndex: 0, explanation: 'R-R ficam em sílabas diferentes.' },
    { subject: 'Gramática', question: 'O que é o sujeito indeterminado?', options: ['Não se pode ou quer identificar', 'É implícito', 'Não existe', 'É o "eu"'], correctAnswerIndex: 0, explanation: 'Ex: "Disseram que..." ou "Precisa-se de..."' }
  ]
};
