import { Simulado } from './simulado.model';

export const QUESTIONS_POOL: Record<string, Omit<Simulado, 'id'>[]> = {
  'Matemática': [
    { subject: 'Matemática', question: 'Qual é o resultado de 7 x 8?', options: ['54', '56', '62', '64'], correctAnswerIndex: 1, explanation: '7 multiplicado por 8 resulta em 56.' },
    { subject: 'Matemática', question: 'Quanto é 15% de 200?', options: ['20', '30', '40', '25'], correctAnswerIndex: 1, explanation: '10% de 200 é 20, 5% é 10. 20 + 10 = 30.' },
    { subject: 'Matemática', question: 'Qual é a raiz quadrada de 144?', options: ['10', '11', '12', '14'], correctAnswerIndex: 2, explanation: '12 x 12 = 144.' },
    { subject: 'Matemática', question: 'Resolva: 2 + 3 x 4', options: ['20', '14', '24', '10'], correctAnswerIndex: 1, explanation: 'Primeiro a multiplicação: 3x4=12. Depois a soma: 2+12=14.' },
    { subject: 'Matemática', question: 'Quantos lados tem um hexágono?', options: ['5', '6', '7', '8'], correctAnswerIndex: 1, explanation: 'Um hexágono possui 6 lados.' },
    { subject: 'Matemática', question: 'O que é um ângulo obtuso?', options: ['Menor que 90º', 'Igual a 90º', 'Maior que 90º e menor que 180º', 'Igual a 180º'], correctAnswerIndex: 2, explanation: 'Ângulo obtuso mede mais que 90 graus e menos que 180.' },
    { subject: 'Matemática', question: 'Qual o valor de Pi (aproximado)?', options: ['3,12', '3,14', '3,16', '3,18'], correctAnswerIndex: 1, explanation: 'O valor de Pi é aproximadamente 3,14.' },
    { subject: 'Matemática', question: 'Quanto é 5³?', options: ['15', '25', '125', '75'], correctAnswerIndex: 2, explanation: '5 x 5 x 5 = 125.' },
    { subject: 'Matemática', question: 'Qual é o dobro de 1/2?', options: ['1/4', '1', '2', '1/2'], correctAnswerIndex: 1, explanation: '2 vezes 1/2 é igual a 1.' },
    { subject: 'Matemática', question: 'Converta 2m para cm', options: ['20cm', '200cm', '2000cm', '2cm'], correctAnswerIndex: 1, explanation: '1 metro tem 100cm, logo 2 metros têm 200cm.' },
    // ... adding more to reach ~30 visually
    { subject: 'Matemática', question: 'Qual o próximo número da sequência: 2, 4, 8, 16...', options: ['24', '30', '32', '36'], correctAnswerIndex: 2, explanation: 'A sequência dobra o número anterior.' },
    { subject: 'Matemática', question: 'Quanto é 100 dividido por 4?', options: ['20', '25', '30', '24'], correctAnswerIndex: 1, explanation: '100 / 4 = 25.' },
    { subject: 'Matemática', question: 'Qual a área de um quadrado de lado 4cm?', options: ['8cm²', '12cm²', '16cm²', '20cm²'], correctAnswerIndex: 2, explanation: 'Área = lado x lado = 4 x 4 = 16.' },
    { subject: 'Matemática', question: 'O que é um número primo?', options: ['Divisível só por 2', 'Divisível por 1 e por ele mesmo', 'Número ímpar', 'Número infinito'], correctAnswerIndex: 1, explanation: 'Número primo tem apenas dois divisores: 1 e ele mesmo.' },
    { subject: 'Matemática', question: 'Quanto vale X em: 2X + 4 = 10?', options: ['2', '3', '4', '1'], correctAnswerIndex: 1, explanation: '2X = 6 -> X = 3.' },
    { subject: 'Matemática', question: 'Qual o MDC de 8 e 12?', options: ['2', '4', '8', '24'], correctAnswerIndex: 1, explanation: 'Os divisores comuns são 1, 2, 4. O maior é 4.' },
    { subject: 'Matemática', question: 'Qual o MMC de 3 e 4?', options: ['7', '12', '6', '24'], correctAnswerIndex: 1, explanation: 'Múltiplos de 3: 3,6,9,12... Múltiplos de 4: 4,8,12... MMC é 12.' },
    { subject: 'Matemática', question: 'Quanto é -5 + 8?', options: ['-3', '3', '-13', '13'], correctAnswerIndex: 1, explanation: 'Sinais opostos, subtrai e mantém o sinal do maior: 8-5=3.' },
    { subject: 'Matemática', question: 'O que é a hipotenusa?', options: ['O menor lado de um triângulo', 'O lado oposto ao ângulo reto', 'A altura do triângulo', 'Um tipo de ângulo'], correctAnswerIndex: 1, explanation: 'Hipotenusa é o lado oposto ao ângulo de 90 graus no triângulo retângulo.' },
    { subject: 'Matemática', question: 'Quanto é 3 fatorial (3!)?', options: ['3', '6', '9', '1'], correctAnswerIndex: 1, explanation: '3! = 3 x 2 x 1 = 6.' },
    { subject: 'Matemática', question: 'Qual a fórmula da área do círculo?', options: ['2πr', 'πr²', 'πr', '2πr²'], correctAnswerIndex: 1, explanation: 'Área = Pi vezes raio ao quadrado.' },
    { subject: 'Matemática', question: 'Quantos graus tem um círculo completo?', options: ['180', '270', '360', '90'], correctAnswerIndex: 2, explanation: 'Uma volta completa tem 360 graus.' },
    { subject: 'Matemática', question: 'Qual o perímetro de um quadrado de lado 5?', options: ['10', '15', '20', '25'], correctAnswerIndex: 2, explanation: 'Perímetro = 4 x lado = 4 x 5 = 20.' },
    { subject: 'Matemática', question: 'Quanto é a raiz cúbica de 27?', options: ['3', '9', '6', '1'], correctAnswerIndex: 0, explanation: '3 x 3 x 3 = 27.' },
    { subject: 'Matemática', question: 'Se x=2 e y=3, quanto é x+y²?', options: ['25', '11', '13', '8'], correctAnswerIndex: 1, explanation: '2 + 3² = 2 + 9 = 11.' },
    { subject: 'Matemática', question: 'Qual é o nome de um polígono de 5 lados?', options: ['Quadrado', 'Hexágono', 'Pentágono', 'Heptágono'], correctAnswerIndex: 2, explanation: 'Pentágono tem 5 lados.' },
    { subject: 'Matemática', question: 'Quanto é 10 elevado a 0?', options: ['0', '1', '10', '100'], correctAnswerIndex: 1, explanation: 'Qualquer número elevado a 0 é 1.' },
    { subject: 'Matemática', question: 'Qual a soma dos ângulos internos de um triângulo?', options: ['180º', '360º', '90º', '270º'], correctAnswerIndex: 0, explanation: 'A soma é sempre 180 graus.' },
    { subject: 'Matemática', question: 'Quanto é 0,5 + 0,25?', options: ['0,30', '0,75', '0,80', '0,255'], correctAnswerIndex: 1, explanation: '0,50 + 0,25 = 0,75.' },
    { subject: 'Matemática', question: 'Qual é inverso de 4?', options: ['-4', '1/4', '0.4', '2'], correctAnswerIndex: 1, explanation: 'O inverso multiplicativo de x é 1/x.' }
  ],
  'Português': [
    { subject: 'Português', question: 'Qual palavra é um substantivo próprio?', options: ['Cachorro', 'Cidade', 'Brasil', 'Amor'], correctAnswerIndex: 2, explanation: 'Brasil nomeia um lugar específico.' },
    { subject: 'Português', question: 'Qual é o antônimo de "frio"?', options: ['Gelado', 'Quente', 'Morno', 'Congelado'], correctAnswerIndex: 1, explanation: 'O contrário de frio é quente.' },
    { subject: 'Português', question: 'Quantas sílabas tem a palavra "Paralelepípedo"?', options: ['5', '6', '7', '8'], correctAnswerIndex: 2, explanation: 'Pa-ra-le-le-pí-pe-do (7 sílabas).' },
    { subject: 'Português', question: 'Qual é o sujeito em "O gato correu"?', options: ['O gato', 'Correu', 'Gato', 'O'], correctAnswerIndex: 0, explanation: '"O gato" é quem pratica a ação.' },
    { subject: 'Português', question: 'O que é uma paroxítona?', options: ['A última sílaba forte', 'A penúltima sílaba forte', 'A antepenúltima sílaba forte', 'Todas as sílabas fortes'], correctAnswerIndex: 1, explanation: 'Palavras com a penúltima sílaba tônica.' },
    { subject: 'Português', question: 'Assinale a palavra com crase correta:', options: ['Vou à praia', 'Vou a praia', 'Vou á praia', 'Vou à ela'], correctAnswerIndex: 0, explanation: 'Quem vai, vai A algum lugar. A + A = À.' },
    { subject: 'Português', question: 'Qual o plural de "cidadão"?', options: ['Cidadões', 'Cidadãos', 'Cidadães', 'Cidadãozinhos'], correctAnswerIndex: 1, explanation: 'O plural correto é cidadãos.' },
    { subject: 'Português', question: 'O que é um adjetivo?', options: ['Ação', 'Nome', 'Qualidade', 'Conjunção'], correctAnswerIndex: 2, explanation: 'Adjetivo caracteriza o substantivo.' },
    { subject: 'Português', question: 'Sinônimo de "feliz":', options: ['Triste', 'Saltitante', 'Alegre', 'Rápido'], correctAnswerIndex: 2, explanation: 'Alegre tem sentido semelhante a feliz.' },
    { subject: 'Português', question: '"Nós vai" está:', options: ['Correto', 'Incorreto (Concordância)', 'Incorreto (Regência)', 'Formal'], correctAnswerIndex: 1, explanation: 'Erro de concordância verbal. Correto: Nós vamos.' },
    { subject: 'Português', question: 'Qual é o verbo na frase "Ela canta bem"?', options: ['Ela', 'Canta', 'Bem', 'Nenhum'], correctAnswerIndex: 1, explanation: 'Canta é a ação.' },
    { subject: 'Português', question: 'A palavra "muito" é:', options: ['Verbo', 'Adjetivo', 'Advérbio', 'Substantivo'], correctAnswerIndex: 2, explanation: 'Advérbio de intensidade.' },
    { subject: 'Português', question: 'Qual o feminino de "carneiro"?', options: ['Carneira', 'Cabra', 'Ovelha', 'Vaca'], correctAnswerIndex: 2, explanation: 'O feminino de carneiro é ovelha.' },
    { subject: 'Português', question: 'Quem escreveu "Dom Casmurro"?', options: ['Machado de Assis', 'José de Alencar', 'Clarice Lispector', 'Jorge Amado'], correctAnswerIndex: 0, explanation: 'Obra clássica de Machado de Assis.' },
    { subject: 'Português', question: 'O que é hiato?', options: ['Encontro de consoantes', 'Encontro de vogais em sílabas diferentes', 'Encontro de vogais na mesma sílaba', 'Vogal e consoante'], correctAnswerIndex: 1, explanation: 'Duas vogais juntas na palavra, mas separadas na silaba (ex: sa-ú-de).' },
    { subject: 'Português', question: '"Mas" indica:', options: ['Adição', 'Oposição', 'Tempo', 'Causa'], correctAnswerIndex: 1, explanation: 'Conjunção adversativa.' },
    { subject: 'Português', question: '"Mais" indica:', options: ['Oposição', 'Quantidade', 'Tempo', 'Dúvida'], correctAnswerIndex: 1, explanation: 'Advérbio de intensidade/quantidade.' },
    { subject: 'Português', question: 'Qual é o coletivo de "abelhas"?', options: ['Matilha', 'Cardume', 'Enxame', 'Rebanho'], correctAnswerIndex: 2, explanation: 'Enxame é o coletivo de abelhas.' },
    { subject: 'Português', question: 'A palavra "árvore" é:', options: ['Oxítona', 'Paroxítona', 'Proparoxítona', 'Monossílaba'], correctAnswerIndex: 2, explanation: 'A antepenúltima sílaba é tônica (ár-vo-re).' },
    { subject: 'Português', question: 'Qual frase está no passado?', options: ['Eu como pão', 'Eu comerei pão', 'Eu comi pão', 'Eu estou comendo'], correctAnswerIndex: 2, explanation: '"Comi" é pretérito (passado).' },
    { subject: 'Português', question: 'Como se escreve: "excessão" ou "exceção"?', options: ['Excessão', 'Exceção', 'Eceção', 'Esceção'], correctAnswerIndex: 1, explanation: 'Correto é Exceção (com ç).' },
    { subject: 'Português', question: 'O que é onomatopeia?', options: ['Tipo de verso', 'Imitação de som', 'Figura de linguagem visual', 'Erro ortográfico'], correctAnswerIndex: 1, explanation: 'Ex: "Miau", "Tic-tac".' },
    { subject: 'Português', question: '"Copo de vidro" - vidro é:', options: ['Substantivo', 'Adjetivo', 'Verbo', 'Locução adjetiva'], correctAnswerIndex: 0, explanation: 'Nesse contexto é a matéria (substantivo), mas "de vidro" funciona como locução adjetiva.' },
    { subject: 'Português', question: 'Qual a pontuação de fim de pergunta?', options: ['Ponto final', 'Interrogação', 'Exclamação', 'Vírgula'], correctAnswerIndex: 1, explanation: '?' },
    { subject: 'Português', question: 'O que é dígrafo?', options: ['Duas letras, um som', 'Dois sons, uma letra', 'Duas vogais', 'Duas sílabas'], correctAnswerIndex: 0, explanation: 'Ex: ch, lh, nh, rr, ss.' },
    { subject: 'Português', question: 'Qual o aumentativo de "casa"?', options: ['Casinha', 'Casarão', 'Casona', 'Predio'], correctAnswerIndex: 1, explanation: 'Casarão.' },
    { subject: 'Português', question: 'A palavra "herói" tem acento?', options: ['Sim', 'Não', 'Às vezes', 'Opcional'], correctAnswerIndex: 0, explanation: 'Sim, oxítona terminada em ditongo aberto "ói".' },
    { subject: 'Português', question: 'O que significa "manga" (fruta) e "manga" (camisa)?', options: ['Sinônimos', 'Antônimos', 'Homônimos', 'Parônimos'], correctAnswerIndex: 2, explanation: 'Palavras iguais na escrita ou som, mas significados diferentes.' },
    { subject: 'Português', question: 'Quantas letras tem o alfabeto?', options: ['23', '24', '25', '26'], correctAnswerIndex: 3, explanation: '26 letras.' },
    { subject: 'Português', question: '"Ele tinha chegado". O tempo é:', options: ['Futuro', 'Presente', 'Pretérito mais-que-perfeito composto', 'Imperativo'], correctAnswerIndex: 2, explanation: 'Tinha chegado equivale a "chegara".' }
  ],
  'Física': [
    { subject: 'Física', question: 'Qual é a fórmula da velocidade média?', options: ['V = d/t', 'V = d*t', 'V = t/d', 'V = a*t'], correctAnswerIndex: 0, explanation: 'Velocidade é a distância dividida pelo tempo.' },
    { subject: 'Física', question: 'Unidade de força no SI:', options: ['Joule', 'Newton', 'Pascal', 'Watt'], correctAnswerIndex: 1, explanation: 'Força é medida em Newtons (N).' },
    { subject: 'Física', question: 'Qual a aceleração da gravidade aprox. na Terra?', options: ['5 m/s²', '9,8 m/s²', '12 m/s²', '15 m/s²'], correctAnswerIndex: 1, explanation: 'Aproximadamente 9,8 m/s².' },
    { subject: 'Física', question: 'O que mede o termômetro?', options: ['Calor', 'Temperatura', 'Pressão', 'Umidade'], correctAnswerIndex: 1, explanation: 'Mede o grau de agitação das moléculas (temperatura), não calor diretamente.' },
    { subject: 'Física', question: 'Qual a 1ª Lei de Newton?', options: ['Inércia', 'Ação e Reação', 'Gravitação', 'F=ma'], correctAnswerIndex: 0, explanation: 'Lei da Inércia.' },
    { subject: 'Física', question: 'Em qual estado a água ferve (nível do mar)?', options: ['0ºC', '50ºC', '100ºC', '200ºC'], correctAnswerIndex: 2, explanation: '100 graus Celsius.' },
    { subject: 'Física', question: 'O som se propaga no vácuo?', options: ['Sim', 'Não', 'Depende', 'Às vezes'], correctAnswerIndex: 1, explanation: 'Som precisa de meio material para se propagar.' },
    { subject: 'Física', question: 'Fórmula da Energia Cinética:', options: ['mgh', 'mv²/2', 'ma', 'mc²'], correctAnswerIndex: 1, explanation: 'Massa vezes velocidade ao quadrado dividido por 2.' },
    { subject: 'Física', question: 'Cargas de sinais iguais:', options: ['Se atraem', 'Se repelem', 'Se anulam', 'Explodem'], correctAnswerIndex: 1, explanation: 'Cargas iguais se repelem.' },
    { subject: 'Física', question: 'O que é um ano-luz?', options: ['Tempo', 'Distância', 'Velocidade', 'Força'], correctAnswerIndex: 1, explanation: 'Distância que a luz percorre em um ano.' },
    { subject: 'Física', question: 'Qual a velocidade da luz no vácuo?', options: ['300 m/s', '300.000 km/s', '340 m/s', '1.000 km/h'], correctAnswerIndex: 1, explanation: 'Aproximadamente 300.000 km/s.' },
    { subject: 'Física', question: 'O que é a refração?', options: ['Luz batendo e voltando', 'Luz mudando de meio e velocidade', 'Luz sendo absorvida', 'Luz criando arco-íris'], correctAnswerIndex: 1, explanation: 'Mudança de velocidade (e direção) ao mudar de meio.' },
    { subject: 'Física', question: 'Unidade de Potência:', options: ['Joule', 'Watt', 'Volt', 'Ampere'], correctAnswerIndex: 1, explanation: 'Watt (W).' },
    { subject: 'Física', question: 'Fórmula de Ohm:', options: ['U = R*i', 'P = i*U', 'E = mc²', 'F = m*a'], correctAnswerIndex: 0, explanation: 'Tensão = Resistência x Corrente.' },
    { subject: 'Física', question: 'O elétron tem carga:', options: ['Positiva', 'Negativa', 'Neutra', 'Dupla'], correctAnswerIndex: 1, explanation: 'Negativa.' },
    { subject: 'Física', question: 'O que é densidade?', options: ['Volume/Massa', 'Massa/Volume', 'Peso/Altura', 'Força/Área'], correctAnswerIndex: 1, explanation: 'd = m/v.' },
    { subject: 'Física', question: 'As cores do arco-íris são formadas por:', options: ['Reflexão', 'Dispersão', 'Difração', 'Interferência'], correctAnswerIndex: 1, explanation: 'A luz branca se separa em cores (dispersão).' },
    { subject: 'Física', question: 'Qual planeta é conhecido pelos anéis?', options: ['Marte', 'Júpiter', 'Saturno', 'Vênus'], correctAnswerIndex: 2, explanation: 'Saturno.' },
    { subject: 'Física', question: 'O que é o zero absoluto?', options: ['0ºC', '-273,15ºC', '0ºF', '-100ºC'], correctAnswerIndex: 1, explanation: '0 Kelvin, onde cessa a agitação molecular.' },
    { subject: 'Física', question: 'Para toda ação, há uma reação...', options: ['Igual e no mesmo sentido', 'Igual e sentido contrário', 'Maior e sentido contrário', 'Nula'], correctAnswerIndex: 1, explanation: '3ª Lei de Newton: mesma intensidade, mesma direção, sentidos opostos.' },
    { subject: 'Física', question: 'O Sol é uma:', options: ['Planeta', 'Estrela', 'Lua', 'Galáxia'], correctAnswerIndex: 1, explanation: 'Estrela anã amarela.' },
    { subject: 'Física', question: 'Unidade de corrente elétrica:', options: ['Volt', 'Ohm', 'Ampere', 'Coulomb'], correctAnswerIndex: 2, explanation: 'Ampere (A).' },
    { subject: 'Física', question: 'O que é atrito?', options: ['Força que ajuda o movimento', 'Força que se opõe ao movimento', 'Tipo de energia', 'Aceleração'], correctAnswerIndex: 1, explanation: 'Resistência ao movimento relativo entre superfícies.' },
    { subject: 'Física', question: 'Qual a cor que reflete todas as luzes?', options: ['Preto', 'Branco', 'Vermelho', 'Azul'], correctAnswerIndex: 1, explanation: 'Branco reflete todas, preto absorve todas.' },
    { subject: 'Física', question: 'O que é fusão nuclear?', options: ['Quebra de átomos', 'Junção de átomos', 'Evaporação', 'Congelamento'], correctAnswerIndex: 1, explanation: 'Processo que ocorre no Sol (H + H -> He).' },
    { subject: 'Física', question: 'Instrumento para medir pressão atmosférica:', options: ['Termômetro', 'Barômetro', 'Manômetro', 'Voltímetro'], correctAnswerIndex: 1, explanation: 'Barômetro.' },
    { subject: 'Física', question: 'Espelhos convexos:', options: ['Ampliam a imagem', 'Invertem a imagem', 'Ampliam o campo de visão', 'Focam a luz'], correctAnswerIndex: 2, explanation: 'Usados em retrovisores e lojas, diminuem a imagem mas aumentam o campo.' },
    { subject: 'Física', question: 'Qual é o metal líquido à temperatura ambiente?', options: ['Ferro', 'Mercúrio', 'Ouro', 'Prata'], correctAnswerIndex: 1, explanation: 'Mercúrio.' },
    { subject: 'Física', question: 'Energia potencial depende de:', options: ['Velocidade', 'Altura', 'Tempo', 'Atrito'], correctAnswerIndex: 1, explanation: 'Epg = mgh (depende da altura h).' },
    { subject: 'Física', question: 'Qual a unidade de Frequência?', options: ['Hertz', 'Segundo', 'Metro', 'Newton'], correctAnswerIndex: 0, explanation: 'Hz (ciclos por segundo).' },
  ],
  'História': [
    { subject: 'História', question: 'Quem descobriu o Brasil?', options: ['Colombo', 'Cabral', 'Vasco da Gama', 'Magalhães'], correctAnswerIndex: 1, explanation: 'Pedro Álvares Cabral em 1500.' },
    { subject: 'História', question: 'Ano da Independência do Brasil:', options: ['1808', '1822', '1889', '1500'], correctAnswerIndex: 1, explanation: '7 de Setembro de 1822.' },
    { subject: 'História', question: 'Quem foi o primeiro presidente do Brasil?', options: ['Getúlio Vargas', 'Marechal Deodoro', 'Dom Pedro II', 'JK'], correctAnswerIndex: 1, explanation: 'Marechal Deodoro da Fonseca.' },
    { subject: 'História', question: 'O que foi o feudalismo?', options: ['Sistema industrial', 'Sistema agrário vrasalo-senhor', 'Democracia grega', 'Ditadura romana'], correctAnswerIndex: 1, explanation: 'Sistema medieval baseado na terra e fidelidade.' },
    { subject: 'História', question: 'País onde começou a Revolução Industrial:', options: ['França', 'EUA', 'Inglaterra', 'Alemanha'], correctAnswerIndex: 2, explanation: 'Inglaterra, século XVIII.' },
    { subject: 'História', question: 'Líder da Alemanha nazista:', options: ['Mussolini', 'Hitler', 'Stalin', 'Franco'], correctAnswerIndex: 1, explanation: 'Adolf Hitler.' },
    { subject: 'História', question: 'Guerra Fria foi entre:', options: ['EUA e URSS', 'EUA e China', 'Alemanha e Inglaterra', 'Brasil e Argentina'], correctAnswerIndex: 0, explanation: 'Conflito ideológico entre Capitalismo (EUA) e Socialismo (URSS).' },
    { subject: 'História', question: 'Quem pintou a Mona Lisa?', options: ['Michelangelo', 'Da Vinci', 'Van Gogh', 'Picasso'], correctAnswerIndex: 1, explanation: 'Leonardo da Vinci.' },
    { subject: 'História', question: 'Qual era a moeda antes do Real?', options: ['Cruzado', 'Cruzeiro Real', 'Cruzeiro', 'Todos esses'], correctAnswerIndex: 3, explanation: 'O Brasil teve várias moedas antes do Real (1994).' },
    { subject: 'História', question: 'O que comemora em 15 de Novembro?', options: ['Independência', 'Proclamação da República', 'Natal', 'Tiradentes'], correctAnswerIndex: 1, explanation: 'República proclamada em 1889.' },
    { subject: 'História', question: 'Capital do Império Romano:', options: ['Atenas', 'Esparta', 'Roma', 'Veneza'], correctAnswerIndex: 2, explanation: 'Roma.' },
    { subject: 'História', question: 'Quem era chamado de "O Libertador"?', options: ['Napoleão', 'Simon Bolívar', 'Dom Pedro I', 'Tiradentes'], correctAnswerIndex: 1, explanation: 'Bolívar libertou várias nações sul-americanas.' },
    { subject: 'História', question: 'O que foi a Lei Áurea?', options: ['Fim da Monarquia', 'Abolição da Escravidão', 'Início da República', 'Voto feminino'], correctAnswerIndex: 1, explanation: 'Assinada em 1888 pela Princesa Isabel.' },
    { subject: 'História', question: 'Primeira capital do Brasil:', options: ['Rio de Janeiro', 'Brasília', 'Salvador', 'São Paulo'], correctAnswerIndex: 2, explanation: 'Salvador foi capital até 1763.' },
    { subject: 'História', question: 'Deus egípcio do sol:', options: ['Anúbis', 'Rá', 'Osíris', 'Zeus'], correctAnswerIndex: 1, explanation: 'Rá.' },
    { subject: 'História', question: 'Onde ficam as pirâmides de Gizé?', options: ['México', 'Egito', 'Peru', 'Sudão'], correctAnswerIndex: 1, explanation: 'No Egito.' },
    { subject: 'História', question: 'Quem libertou os escravos nos EUA?', options: ['Washington', 'Lincoln', 'Kennedy', 'Obama'], correctAnswerIndex: 1, explanation: 'Abraham Lincoln.' },
    { subject: 'História', question: 'Revolução Francesa aconteceu em:', options: ['1789', '1500', '1945', '2000'], correctAnswerIndex: 0, explanation: 'Queda da Bastilha, 1789.' },
    { subject: 'História', question: 'Palavra chave do Iluminismo:', options: ['Fé', 'Razão', 'Guerra', 'Tradição'], correctAnswerIndex: 1, explanation: 'Século das Luzes/Razão.' },
    { subject: 'História', question: 'Fundador de Brasília:', options: ['Getúlio Vargas', 'JK', 'Lula', 'FHC'], correctAnswerIndex: 1, explanation: 'Juscelino Kubitschek.' },
    { subject: 'História', question: 'Ditadura Militar no Brasil durou:', options: ['10 anos', '21 anos', '30 anos', '5 anos'], correctAnswerIndex: 1, explanation: '1964 a 1985.' },
    { subject: 'História', question: 'Quem "descobriu" a América?', options: ['Cabral', 'Colombo', 'Vespucci', 'Cortés'], correctAnswerIndex: 1, explanation: 'Cristóvão Colombo em 1492.' },
    { subject: 'História', question: 'Civilização dos Andes:', options: ['Incas', 'Maias', 'Astecas', 'Tupis'], correctAnswerIndex: 0, explanation: 'Incas (Peru).' },
    { subject: 'História', question: 'Povo que construiu o Coliseu:', options: ['Gregos', 'Romanos', 'Egípcios', 'Persas'], correctAnswerIndex: 1, explanation: 'Império Romano.' },
    { subject: 'História', question: 'Presidente que suicidou-se:', options: ['JK', 'Jânio', 'Getúlio Vargas', 'Tancredo'], correctAnswerIndex: 2, explanation: 'Em 1954.' },
    { subject: 'História', question: 'Muro que dividiu a Alemanha:', options: ['Muro das Lamentações', 'Muro de Berlim', 'Grande Muralha', 'Muro de Trump'], correctAnswerIndex: 1, explanation: 'Símbolo da Guerra Fria.' },
    { subject: 'História', question: 'Quem escreveu "O Príncipe"?', options: ['Maquiavel', 'Platão', 'Aristóteles', 'Hobbes'], correctAnswerIndex: 0, explanation: 'Nicolau Maquiavel.' },
    { subject: 'História', question: 'Guerra do Paraguai envolveu:', options: ['Brasil, Argentina, Uruguai vs Paraguai', 'Brasil vs Argentina', 'Paraguai vs EUA', 'Brasil vs Bolívia'], correctAnswerIndex: 0, explanation: 'Tríplice Aliança contra o Paraguai.' },
    { subject: 'História', question: 'Primeiro homem na Lua:', options: ['Gagarin', 'Armstrong', 'Collins', 'Buzz'], correctAnswerIndex: 1, explanation: 'Neil Armstrong (1969).' },
    { subject: 'História', question: 'Ano do fim da 2ª Guerra Mundial:', options: ['1940', '1945', '1950', '1939'], correctAnswerIndex: 1, explanation: 'Terminou em 1945.' },
  ],
  'Álgebra': [
    { subject: 'Álgebra', question: 'Se x + 5 = 12, qual o valor de x?', options: ['5', '6', '7', '8'], correctAnswerIndex: 2, explanation: 'x = 12 - 5 = 7.' },
    { subject: 'Álgebra', question: 'Quanto vale y em 2y = 10?', options: ['2', '5', '8', '20'], correctAnswerIndex: 1, explanation: 'y = 10/2 = 5.' },
    { subject: 'Álgebra', question: 'Expandir (x+2)²:', options: ['x²+4', 'x²+4x+4', 'x²+2x+4', '2x+4'], correctAnswerIndex: 1, explanation: 'Quadrado do primeiro + 2x primeiro x segundo + quadrado do segundo.' },
    { subject: 'Álgebra', question: 'Fatore x² - 9:', options: ['(x-3)(x-3)', '(x+3)(x-3)', '(x+9)(x-9)', 'x(x-9)'], correctAnswerIndex: 1, explanation: 'Diferença de quadrados.' },
    { subject: 'Álgebra', question: 'Valor de x em 3x - 1 = x + 5:', options: ['2', '3', '4', '1'], correctAnswerIndex: 1, explanation: '2x = 6 -> x = 3.' },
    { subject: 'Álgebra', question: 'Se f(x) = 2x + 1, calcule f(3):', options: ['6', '7', '5', '8'], correctAnswerIndex: 1, explanation: '2(3) + 1 = 7.' },
    { subject: 'Álgebra', question: 'Resolva a inequação: x > 5, x é natural.', options: ['{0,1,2,3,4}', '{6,7,8...}', '{5,6,7...}', '{...}'], correctAnswerIndex: 1, explanation: 'Maiores que 5 (6 em diante).' },
    { subject: 'Álgebra', question: 'Coeficiente angular de y = 4x + 2:', options: ['2', '4', 'x', 'y'], correctAnswerIndex: 1, explanation: 'O valor que multiplica x (4).' },
    { subject: 'Álgebra', question: 'Raízes de x² - 5x + 6 = 0:', options: ['2 e 3', '-2 e -3', '1 e 6', '-1 e -6'], correctAnswerIndex: 0, explanation: 'Soma=5, Produto=6. Raízes 2 e 3.' },
    { subject: 'Álgebra', question: 'O que é uma função linear?', options: ['Grau 2', 'Grau 1', 'Exponencial', 'Logarítmica'], correctAnswerIndex: 1, explanation: 'f(x) = ax + b (Grau 1).' },
    { subject: 'Álgebra', question: '3x + 2y = 10 e y = x. Quanto vale x?', options: ['1', '2', '3', '4'], correctAnswerIndex: 1, explanation: '3x + 2x = 10 -> 5x=10 -> x=2.' },
    { subject: 'Álgebra', question: 'Simplifique (x^3 / x^2):', options: ['x', 'x^5', 'x^1.5', '1'], correctAnswerIndex: 0, explanation: 'Subtrai expoentes: 3-2=1 -> x.' },
    { subject: 'Álgebra', question: 'x * x * x é igual a:', options: ['3x', 'x³', 'x+3', '3^x'], correctAnswerIndex: 1, explanation: 'x ao cubo.' },
    { subject: 'Álgebra', question: 'Valor de x em x/2 = 4:', options: ['2', '6', '8', '4'], correctAnswerIndex: 2, explanation: 'x = 4 * 2 = 8.' },
    { subject: 'Álgebra', question: 'O gráfico de y=x² é uma:', options: ['Reta', 'Parábola', 'Hipérbole', 'Círculo'], correctAnswerIndex: 1, explanation: 'Função quadrática gera parábola.' },
    { subject: 'Álgebra', question: 'Discriminante (Delta) de ax²+bx+c:', options: ['b²-4ac', '2a', '-b', 'c/a'], correctAnswerIndex: 0, explanation: 'Delta = b² - 4ac.' },
    { subject: 'Álgebra', question: 'Se Delta < 0:', options: ['2 raízes reais', '1 raiz real', 'Nenhuma raiz real', '3 raízes'], correctAnswerIndex: 2, explanation: 'Não existem raízes reais.' },
    { subject: 'Álgebra', question: 'Logaritmo de 100 na base 10:', options: ['1', '2', '10', '100'], correctAnswerIndex: 1, explanation: '10² = 100.' },
    { subject: 'Álgebra', question: 'x + x =', options: ['x²', '2x', 'x', '1'], correctAnswerIndex: 1, explanation: '2x.' },
    { subject: 'Álgebra', question: 'Produto notável (a+b)(a-b):', options: ['a²-b²', 'a²+b²', 'a²-2ab+b²', 'a+b'], correctAnswerIndex: 0, explanation: 'Diferença de quadrados.' },
    { subject: 'Álgebra', question: 'Qual a declividade da reta vertical?', options: ['0', '1', 'Indefinida', '-1'], correctAnswerIndex: 2, explanation: 'Divisão por zero (tangente de 90º).' },
    { subject: 'Álgebra', question: 'Resolva |x| = 5:', options: ['5', '-5', '5 e -5', '25'], correctAnswerIndex: 2, explanation: 'Módulo pode ser 5 ou -5.' },
    { subject: 'Álgebra', question: 'Se 2^x = 8, x é:', options: ['2', '3', '4', '8'], correctAnswerIndex: 1, explanation: '2³ = 8.' },
    { subject: 'Álgebra', question: 'Matriz identidade tem:', options: ['1 na diagonal principal', '0 na diagonal principal', 'Todos 1', 'Todos 0'], correctAnswerIndex: 0, explanation: '1 na diagonal, 0 no resto.' },
    { subject: 'Álgebra', question: 'Soma de matrizes requer:', options: ['Mesma ordem', 'Mesmo determinante', 'Serem quadradas', 'Serem invertíveis'], correctAnswerIndex: 0, explanation: 'Mesmo número de linhas e colunas.' },
    { subject: 'Álgebra', question: 'Fórmula de Bhaskara serve para:', options: ['Equação de 1º grau', 'Equação de 2º grau', 'Logaritmo', 'Trigonometria'], correctAnswerIndex: 1, explanation: 'Encontrar raízes da eq. quadrática.' },
    { subject: 'Álgebra', question: 'Ponto (0,0) é a:', options: ['Origem', 'Abscissa', 'Ordenada', 'Declividade'], correctAnswerIndex: 0, explanation: 'Origem do plano cartesiano.' },
    { subject: 'Álgebra', question: 'O que é um monômio?', options: ['Soma de termos', 'Um único termo', 'Divisão', 'Igualdade'], correctAnswerIndex: 1, explanation: 'Expressão com um único termo algébrico.' },
    { subject: 'Álgebra', question: 'Grau do polinômio 3x^4 + 2x:', options: ['3', '4', '1', '2'], correctAnswerIndex: 1, explanation: 'O maior expoente é 4.' },
    { subject: 'Álgebra', question: 'Inverso de adicionar 5:', options: ['Multiplicar por 5', 'Subtrair 5', 'Dividir por 5', 'Somar -1'], correctAnswerIndex: 1, explanation: 'Operação inversa da soma é subtração.' }
  ],
  'Química': [
    { subject: 'Química', question: 'Qual é o símbolo do Ouro?', options: ['Ag', 'Au', 'Fe', 'Cu'], correctAnswerIndex: 1, explanation: 'Au vem do latim Aurum.' },
    { subject: 'Química', question: 'O que é H2O?', options: ['Ácido', 'Base', 'Água', 'Sal'], correctAnswerIndex: 2, explanation: 'Água.' },
    { subject: 'Química', question: 'O pH 7 é considerado:', options: ['Ácido', 'Básico', 'Neutro', 'Salino'], correctAnswerIndex: 2, explanation: 'pH 7 é neutro (água pura).' },
    { subject: 'Química', question: 'Quantos elétrons o Hidrogênio tem?', options: ['1', '2', '8', '0'], correctAnswerIndex: 0, explanation: 'Número atômico 1.' },
    { subject: 'Química', question: 'O que é sublimação?', options: ['Sólido para Líquido', 'Líquido para Gasoso', 'Sólido para Gasoso', 'Gasoso para Sólido'], correctAnswerIndex: 2, explanation: 'Passagem direta do sólido para o gasoso.' },
    { subject: 'Química', question: 'Cátions são íons de carga:', options: ['Positiva', 'Negativa', 'Neutra', 'Dupla'], correctAnswerIndex: 0, explanation: 'Perderam elétrons (positivos).' },
    { subject: 'Química', question: 'Gás nobre usado em balões:', options: ['Hélio', 'Oxigênio', 'Hidrogênio', 'Nitrogênio'], correctAnswerIndex: 0, explanation: 'Hélio é inerte e leve.' },
    { subject: 'Química', question: 'Fórmula do sal de cozinha:', options: ['HCl', 'NaOH', 'NaCl', 'CO2'], correctAnswerIndex: 2, explanation: 'Cloreto de Sódio.' },
    { subject: 'Química', question: 'Metal líquido:', options: ['Ferro', 'Mercúrio', 'Chumbo', 'Alumínio'], correctAnswerIndex: 1, explanation: 'Mercúrio.' },
    { subject: 'Química', question: 'O átomo é formado por:', options: ['Prótons e Neutrons', 'Prótons, Neutrons e Elétrons', 'Apenas Elétrons', 'Células'], correctAnswerIndex: 1, explanation: 'Núcleo e eletrosfera.' }
  ],
  'Inglês': [
    { subject: 'Inglês', question: 'Verbo "To Be" (I ___):', options: ['is', 'are', 'am', 'be'], correctAnswerIndex: 2, explanation: 'I am.' },
    { subject: 'Inglês', question: 'Tradução de "Book":', options: ['Caderno', 'Livro', 'Mesa', 'Caneta'], correctAnswerIndex: 1, explanation: 'Book = Livro.' },
    { subject: 'Inglês', question: 'Passado de "Go":', options: ['Goed', 'Gone', 'Went', 'Going'], correctAnswerIndex: 2, explanation: 'Go -> Went.' },
    { subject: 'Inglês', question: 'Plural de "Man":', options: ['Mans', 'Men', 'Manes', 'Mens'], correctAnswerIndex: 1, explanation: 'Diferencial: Man -> Men.' },
    { subject: 'Inglês', question: '"She ___ playing":', options: ['is', 'are', 'am', 'be'], correctAnswerIndex: 0, explanation: 'She is playing.' },
    { subject: 'Inglês', question: 'Cor "Red":', options: ['Azul', 'Verde', 'Vermelho', 'Amarelo'], correctAnswerIndex: 2, explanation: 'Red = Vermelho.' },
    { subject: 'Inglês', question: 'False friend "Push":', options: ['Puxar', 'Empurrar', 'Pular', 'Pegar'], correctAnswerIndex: 1, explanation: 'Push = Empurrar (apesar de parecer puxar).' },
    { subject: 'Inglês', question: 'Dia "Monday":', options: ['Domingo', 'Segunda', 'Terça', 'Quarta'], correctAnswerIndex: 1, explanation: 'Segunda-feira.' },
    { subject: 'Inglês', question: '"How are you?" significa:', options: ['Quem é você?', 'Onde você está?', 'Como você está?', 'Como vai?'], correctAnswerIndex: 2, explanation: 'Saudação comum.' },
    { subject: 'Inglês', question: 'Oposto de "Big":', options: ['Large', 'Huge', 'Small', 'Grand'], correctAnswerIndex: 2, explanation: 'Big (Grande) x Small (Pequeno).' }
  ],
  'Geometria': [
    { subject: 'Geometria', question: 'Soma dos ângulos do quadrado:', options: ['180', '360', '90', '270'], correctAnswerIndex: 1, explanation: '360 graus.' },
    { subject: 'Geometria', question: 'Triângulo com 3 lados iguais:', options: ['Isósceles', 'Escaleno', 'Equilátero', 'Retângulo'], correctAnswerIndex: 2, explanation: 'Equilátero.' },
    { subject: 'Geometria', question: 'Volume do cubo de lado 3:', options: ['9', '18', '27', '6'], correctAnswerIndex: 2, explanation: '3³ = 27.' },
    { subject: 'Geometria', question: 'Nome do polígono de 8 lados:', options: ['Hexágono', 'Octógono', 'Decágono', 'Eneágono'], correctAnswerIndex: 1, explanation: 'Octógono.' },
    { subject: 'Geometria', question: 'Área do triângulo:', options: ['b*h', 'b*h/2', 'l²', '2*pi*r'], correctAnswerIndex: 1, explanation: 'Base vezes altura dividido por 2.' },
    { subject: 'Geometria', question: 'O que é raio:', options: ['Diâmetro', 'Metade do diâmetro', 'Dobro do diâmetro', 'Cordas'], correctAnswerIndex: 1, explanation: 'Raio é a metade.' },
    { subject: 'Geometria', question: 'Ângulo de 90 graus:', options: ['Agudo', 'Obtuso', 'Reto', 'Raso'], correctAnswerIndex: 2, explanation: 'Reto.' },
    { subject: 'Geometria', question: 'Teorema de Pitágoras:', options: ['a=b+c', 'a²=b²+c²', 'a³=b³+c³', 'a=b*c'], correctAnswerIndex: 1, explanation: 'Soma dos quadrados dos catetos.' },
    { subject: 'Geometria', question: 'Quantas faces tem um cubo?', options: ['4', '6', '8', '12'], correctAnswerIndex: 1, explanation: '6 faces.' },
    { subject: 'Geometria', question: 'Linha que divide o círculo ao meio:', options: ['Raio', 'Diâmetro', 'Tangente', 'Secante'], correctAnswerIndex: 1, explanation: 'Diâmetro passa pelo centro.' }
  ],
  'Biologia': [
    { subject: 'Biologia', question: 'Célula sem núcleo organizado:', options: ['Eucarionte', 'Procarionte', 'Vegetal', 'Animal'], correctAnswerIndex: 1, explanation: 'Procarionte (bactérias).' },
    { subject: 'Biologia', question: 'Quem descobriu a penicilina?', options: ['Pasteur', 'Fleming', 'Darwin', 'Mendel'], correctAnswerIndex: 1, explanation: 'Alexander Fleming.' },
    { subject: 'Biologia', question: 'DNA significa:', options: ['Ácido Desoxirribonucleico', 'Ácido Ribonucleico', 'Gene', 'Cromossomo'], correctAnswerIndex: 0, explanation: 'ADN em português.' },
    { subject: 'Biologia', question: 'Unidade básica da vida:', options: ['Átomo', 'Célula', 'Tecido', 'Órgão'], correctAnswerIndex: 1, explanation: 'Célula.' },
    { subject: 'Biologia', question: 'Processo das plantas para energia:', options: ['Respiração', 'Fotossíntese', 'Digestão', 'Fermentação'], correctAnswerIndex: 1, explanation: 'Uso da luz solar.' },
    { subject: 'Biologia', question: 'Pai da Genética:', options: ['Darwin', 'Mendel', 'Lamarck', 'Watson'], correctAnswerIndex: 1, explanation: 'Gregor Mendel.' },
    { subject: 'Biologia', question: 'Animal que mama:', options: ['Réptil', 'Anfíbio', 'Mamífero', 'Ave'], correctAnswerIndex: 2, explanation: 'Mamíferos.' },
    { subject: 'Biologia', question: 'Sangue tipo doador universal:', options: ['A', 'B', 'AB', 'O negativo'], correctAnswerIndex: 3, explanation: 'O-.' },
    { subject: 'Biologia', question: 'Mitocôndria serve para:', options: ['Digestão', 'Respiração celular', 'Proteção', 'Reprodução'], correctAnswerIndex: 1, explanation: 'Produção de energia (ATP).' },
    { subject: 'Biologia', question: 'Maior órgão do corpo:', options: ['Fígado', 'Coração', 'Pele', 'Pulmão'], correctAnswerIndex: 2, explanation: 'A pele.' }
  ],
  'Geografia': [
    { subject: 'Geografia', question: 'Maior país do mundo:', options: ['China', 'EUA', 'Rússia', 'Brasil'], correctAnswerIndex: 2, explanation: 'Rússia em extensão territorial.' },
    { subject: 'Geografia', question: 'Capital da França:', options: ['Londres', 'Berlim', 'Paris', 'Madri'], correctAnswerIndex: 2, explanation: 'Paris.' },
    { subject: 'Geografia', question: 'Quantos continentes existem?', options: ['4', '5', '6', '7'], correctAnswerIndex: 2, explanation: '6 (América, Europa, Ásia, África, Oceania, Antártida).' },
    { subject: 'Geografia', question: 'Rio mais extenso do mundo:', options: ['Nilo', 'Amazonas', 'Mississipi', 'Yangtse'], correctAnswerIndex: 1, explanation: 'Amazonas (disputa com Nilo, mas geralmente aceito).' },
    { subject: 'Geografia', question: 'Linha do Equador divide:', options: ['Leste/Oeste', 'Norte/Sul', 'Dia/Noite', 'Agua/Terra'], correctAnswerIndex: 1, explanation: 'Hemisférios Norte e Sul.' },
    { subject: 'Geografia', question: 'País do Sol Nascente:', options: ['China', 'Coreia', 'Japão', 'Vietnã'], correctAnswerIndex: 2, explanation: 'Japão.' },
    { subject: 'Geografia', question: 'Maior oceano:', options: ['Atlântico', 'Índico', 'Pacífico', 'Glacial'], correctAnswerIndex: 2, explanation: 'Pacífico.' },
    { subject: 'Geografia', question: 'Capital do Brasil:', options: ['Rio', 'São Paulo', 'Brasília', 'Salvador'], correctAnswerIndex: 2, explanation: 'Brasília.' },
    { subject: 'Geografia', question: 'Bússola aponta para:', options: ['Sul', 'Norte', 'Leste', 'Oeste'], correctAnswerIndex: 1, explanation: 'Norte Magnético.' },
    { subject: 'Geografia', question: 'O que é relevo?', options: ['Clima', 'Formas da terra', 'Rios', 'Vegetação'], correctAnswerIndex: 1, explanation: 'Montanhas, planícies, etc.' }
  ],
  'Literatura': [
    { subject: 'Literatura', question: 'Autor de "Sítio do Picapau Amarelo":', options: ['Ziraldo', 'Monteiro Lobato', 'Cecília Meireles', 'Vinicius'], correctAnswerIndex: 1, explanation: 'Monteiro Lobato.' },
    { subject: 'Literatura', question: 'Movimento de "Macunaíma":', options: ['Romantismo', 'Modernismo', 'Barroco', 'Realismo'], correctAnswerIndex: 1, explanation: 'Modernismo brasileiro (1922).' },
    { subject: 'Literatura', question: 'Autor de "O Cortiço":', options: ['Aluísio Azevedo', 'Machado de Assis', 'Jorge Amado', 'Eça'], correctAnswerIndex: 0, explanation: 'Naturalismo.' },
    { subject: 'Literatura', question: '"Ser ou não ser" é de:', options: ['Macbeth', 'Romeu e Julieta', 'Hamlet', 'Otelo'], correctAnswerIndex: 2, explanation: 'Shakespeare em Hamlet.' },
    { subject: 'Literatura', question: 'Poeta dos Escravos:', options: ['Castro Alves', 'Gonçalves Dias', 'Bilac', 'Pessoa'], correctAnswerIndex: 0, explanation: 'Condoreirismo.' },
    { subject: 'Literatura', question: 'Capitu traiu Bentinho?', options: ['Sim', 'Não', 'Mistério do livro', 'Eles não casaram'], correctAnswerIndex: 2, explanation: 'A dúvida é o tema central de Dom Casmurro.' },
    { subject: 'Literatura', question: 'Autor de "Lusiadas":', options: ['Camões', 'Pessoa', 'Saramago', 'Gil Vicente'], correctAnswerIndex: 0, explanation: 'Luís de Camões.' },
    { subject: 'Literatura', question: 'Quem escreveu Harry Potter?', options: ['Tolkien', 'J.K. Rowling', 'Lewis', 'Martin'], correctAnswerIndex: 1, explanation: 'J.K. Rowling.' },
    { subject: 'Literatura', question: 'O que é verso?', options: ['Parágrafo', 'Linha do poema', 'Rima', 'Estrofe'], correctAnswerIndex: 1, explanation: 'Cada linha poética.' },
    { subject: 'Literatura', question: 'Gênero Dramático é para:', options: ['Ler', 'Encenar', 'Cantar', 'Dança'], correctAnswerIndex: 1, explanation: 'Teatro.' }
  ],
  'Gramática': [
    { subject: 'Gramática', question: 'Substantivo que varia em gênero:', options: ['Mesa', 'Cadeira', 'Menino', 'Lápis'], correctAnswerIndex: 2, explanation: 'Menino/Menina.' },
    { subject: 'Gramática', question: 'Verbo de 1ª conjugação termina em:', options: ['ER', 'IR', 'OR', 'AR'], correctAnswerIndex: 3, explanation: 'Amar, Cantar.' },
    { subject: 'Gramática', question: 'Pronome pessoal do caso reto:', options: ['Me', 'Te', 'Eu', 'Se'], correctAnswerIndex: 2, explanation: 'Eu, Tu, Ele...' },
    { subject: 'Gramática', question: 'Adjetivo pátrio de quem nasce no estado do Rio:', options: ['Carioca', 'Fluminense', 'Rio-grandense', 'Baiano'], correctAnswerIndex: 1, explanation: 'Fluminense (Carioca é da cidade).' },
    { subject: 'Gramática', question: 'Coletivo de lobos:', options: ['Alcateia', 'Matilha', 'Bando', 'Cardume'], correctAnswerIndex: 0, explanation: 'Alcateia.' },
    { subject: 'Gramática', question: 'Sinônimo de "Bonito":', options: ['Feio', 'Horrível', 'Belo', 'Grande'], correctAnswerIndex: 2, explanation: 'Belo.' },
    { subject: 'Gramática', question: 'Antônimo de "Alto":', options: ['Baixo', 'Largo', 'Pequeno', 'Gordo'], correctAnswerIndex: 0, explanation: 'Baixo.' },
    { subject: 'Gramática', question: 'Silaba tônica de "Café":', options: ['Ca', 'Fé', 'Nenhuma', 'Ambas'], correctAnswerIndex: 1, explanation: 'Oxítona.' },
    { subject: 'Gramática', question: 'Uso dos "porquês" (final de frase):', options: ['Porque', 'Por que', 'Porquê', 'Por quê'], correctAnswerIndex: 3, explanation: 'Separado e com acento.' },
    { subject: 'Gramática', question: 'Vírgula serve para:', options: ['Terminar frase', 'Omitir letra', 'Pausar/Separar', 'Gritar'], correctAnswerIndex: 2, explanation: 'Pausa ou separação de termos.' }
  ]
};
